### ISSUE TITLE
I was wondering why return in a loop?

### ISSUE THREAD

**Issue by xiekeyi98** [pingcap/chaos-mesh#105]
https://github.com/pingcap/chaos-mesh/blob/cec3b8a64428e4e243c6673555cf9dd21b1d062b/controllers/iochaos/fs/types.go#L192-L207
As the code say, it return anyway in the loop.
But why?

**Comment by cwen0** [comment]
@xiekeyi98 Thanks! this is a bug! Can you help us to fix this?
