### ISSUE TITLE
Weird message output when using kind

### ISSUE THREAD

**Issue by c4pt0r** [pingcap/chaos-mesh#111]
when I was running ./hack/kind-cluster-build.sh, it shows a warning: `kind get kubeconfig-path` is deprecated!
Not sure if the sorftware is successfully installed.

...
############# success create cluster:[kind] #############
To start using your cluster, run:
`kind get kubeconfig-path` is deprecated!

KIND will export and merge kubeconfig like kops, minikube, etc.
This command is now unnecessary and will be removed in a future release.

For more info see: https://github.com/kubernetes-sigs/kind/issues/1060
See also the output of `kind create cluster`

    export KUBECONFIG=/Users/dongxu/.kube/config

dongxu@dongxus-MacBook-Pro ~/gopkg/src/github.com/pingcap/chaos-mesh
master $ kind --version                                                                                                     [15:40:42]
kind version 0.6.1

**Comment by cwen0** [comment]
Thanks for your response,`kind get kubeconfig-path` is now unnecessary and will be removed in a future release.  We will update the kind scripts to avoid the weird message

**Comment by zhouqiang-cl** [comment]
@cwen0 Can this be a "good first issue"

**Comment by cwen0** [comment]
this issue fixed in #140 , I will close this issue
