### ISSUE TITLE
proposal: support restful  API to trigger chaos

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#114]
A friendly HTTP API can be very helpful to use chaos-mesh. We can support APIs such as  triggr request
```
POST /api/v1/network
{
     "type":"partition",
     "source":"1.1.1.1",
     "target":"2.2.2.2",
     ...
}
```

**Comment by siddontang** [comment]
how to trigger chaos?  How does the HTTP API look like?

Can you provide more information?

**Comment by yeya24** [comment]
I believe this should be part of the new chaos-dashboard backend.

**Comment by zhouqiang-cl** [comment]
> I believe this should be part of the new chaos-dashboard backend.

Yes, it should be 👍

**Comment by zhouqiang-cl** [comment]
We also need to give a design proposal for the APIs(what really do we need)

**Comment by zhouqiang-cl** [comment]
@yeya24 I have remove the `good first issue`. We will design for this. Once the design proposal is over, we will add the label `good first issue` again
