### ISSUE TITLE
UCP: Add CPU chaos

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#144]
## Description

In an actual production environment, the CPU may be busy. So there needs to be a way to simulate a busy CPU situation.  Sometimes we need to look at the performance of the server's performance when the CPU is busy. 

So we need to add a new chaos type, namely "CPU chaos". Maybe we can you stress-ng to simulate CPU is busy.

## Score

1679.5

## Mentor(s)

@ethercflow 

## Recommended Skills

* Golang
* stress-ng

## Learning Materials

* [Development guide of chaos-mesh](https://github.com/pingcap/chaos-mesh/wiki/Development-Overview)

**Comment by huangwei2013** [comment]
Found what chaos-cpu/memory support 

> memory:
    --vm 
    --vm-keep
    --vm-bytes
cpu:
    --cpu
    --cpu-load


What if expect more function of stress-ng？ Is there someway to specify more stress-ng options？

**Comment by cwen0** [comment]
@huangwei2013 You can define plenty of stressors by `StressngStresssors`  field, https://github.com/pingcap/chaos-mesh/blob/master/api/v1alpha1/stresschaos_types.go#L63-L70

**Comment by huangwei2013** [comment]
@cwen0  I have read the code and understand this solution. Just to confirm is there some “cheap way” to make use of more stress-ng options

**Comment by cwen0** [comment]
@huangwei2013 Sorry, at present, we only support use this way to make use of more stress-ng options.

**Comment by huangwei2013** [comment]
@cwen0  what about make extend as this format：

>   options: ["--cpu 2", "--timeout 600", "--hdd 1"]

Of course it is no  strict enough but more powerful

**Comment by cwen0** [comment]
@AngleNet How do you think?

**Comment by AngleNet** [comment]
@cwen0 Sorry for the late reply.  I think defining another options for each stressor does not have big advantages over defining one `StressngStressors`. We should extend stressor spec with more powerful features via our own definition of stressor not from `stress-ng`.
