### ISSUE TITLE
UCP: Add memory chaos

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#145]
## Description

Sometimes we should simulate the situation we can not alloc memory. So we need a kind of "chaos" to simulate this situation.

## Score

1679.5

## Mentor(s)

@ethercflow 

## Recommended Skills

* Golang
* Kubernetes

## Learning Materials

* [Development guide of chaos-mesh](https://github.com/pingcap/chaos-mesh/wiki/Development-Overview)

**Comment by AngleNet** [comment]
I'm very interested in this chaos. Any implementation hint or potential solution about this ?

**Comment by zhouqiang-cl** [comment]
@AngleNet sorry for the late update. https://github.com/pingcap/chaos-mesh/pull/273 this pr can do this by bpf

**Comment by zhouqiang-cl** [comment]
@AngleNet My fault. the bpf inject from kernel and works on slab/alloc/etc. but it not simulate lack of memory
If simulate lack of memory. I think you can inject to the pod and eat some memory of the pod

**Comment by zhouqiang-cl** [comment]
And stress-ng may be very helpful to do the memory chaos

**Comment by AngleNet** [comment]
Thank you. I will check that. I'll try to do it.

**Comment by zhouqiang-cl** [comment]
@AngleNet Maybe this simple stress is also very good https://github.com/vishh/stress/blob/master/main.go

**Comment by AngleNet** [comment]
Sorry for the delay. I already checked that. The idea is to eat memory out to get memory allocation failures.

**Comment by AngleNet** [comment]
I think the memory chaos should try to do the following jobs:
1. eats a fixed size of memory of the entire pod to inject the chaos. 
2. free the chaos meory to recover it.
If I'm wrong, please corret me.  @zhouqiang-cl @cwen0

**Comment by zhouqiang-cl** [comment]
> I think the memory chaos should try to do the following jobs:
> 
> 1. eats a fixed size of the memory of the entire pod to inject the chaos.
> 2. free the chaos memory to recover it.
> 
> If I'm wrong, please correct me. @zhouqiang-cl @cwen0

Yes. exactly

**Comment by AngleNet** [comment]
OK. I'm working on it along with #189

**Comment by zhouqiang-cl** [comment]
You can pick it such as run `/pick-up-challenge`
