### ISSUE TITLE
Test Chaos Mesh with Istio

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#146]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Maybe Chaos Mesh can be work with Istio, If it can, we should test it

**Describe the feature you'd like:**

Make Chaos Mesh can work with istio, but first we should test it

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

None

**Comment by siddontang** [comment]
https://istio.io/docs/tasks/traffic-management/fault-injection/

We can also try to integrate the fault injection if user uses Istio.

**Comment by zhouqiang-cl** [comment]
> https://istio.io/docs/tasks/traffic-management/fault-injection/
> 
> We can also try to integrate the fault injection if user uses Istio.

Great idea

**Comment by Yisaer** [comment]
I think `Chaos-Mesh` could make `Istio` as an option component to extend the network chaos for `HTTP` protocol. The only problem How compatible is with the existed `network chaos` and the `Istio` sidecar model.

**Comment by zhouqiang-cl** [comment]
> I think `Chaos-Mesh` could make `Istio` as an option component to extend the network chaos for `HTTP` protocol. The only problem How compatible is with the existed `network chaos` and the `Istio` sidecar model.

can we add a mode in `network chaos` such as `http`

**Comment by linda01232003** [comment]
when I use NetworkChaos  to my exsit istio system ,I find it didn't work.
I expect ping pod ip will delay,but it not delay。
After a while I found my controller inject istio sidecar，I guess it intercept the NetworkChaos  Inject。
The  chaos-daemon log shows that：
kubectl log  chaos-daemon-fzjjg -c  chaos-daemon -n chaos-testing
log is DEPRECATED and will be removed in a future version. Use logs instead.
Chaos-daemon Version: version.Info{GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"a5f2eaabc4c55d07c575577565f6570cd767e8b7", GitTreeState:"dirty", BuildDate:"2020-01-19T10:43:02Z", GoVersion:"go1.13", Compiler:"gc", Platform:"linux/amd64"}
2020-01-20T10:56:10.143Z        INFO    chaos-daemon    starting server
You have mail in /var/spool/mail/root
It can not receive any message。

so I remove the controller sidecar and NetworkChaos  Inject can work。

**Comment by zhouqiang-cl** [comment]
@linda01232003 thank you for your information

**Comment by Yisaer** [comment]
Hi @linda01232003,
AFAIK, there are 2 ways to help you to avoid `Istio` inject sidecar into `Chaos-Mesh`.
The first way is to remove the label of the namespace by:
> kubectl label namespace chaos-testing istio-injection-

And the second way is to annotate the pod with `sidecar.istio.io/inject: "false"` which I had created to issue to help this. https://github.com/pingcap/chaos-mesh/issues/200

**Comment by zhouqiang-cl** [comment]
It works. Tested by @YangKeao
