### ISSUE TITLE
Make Chaos Mesh can run with Istio

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#147]
## Feature Request

**Is your feature request related to a problem? Please describe:**

If Chaos Mesh can run with istio, it will be very helpful to service mesh

**Describe the feature you'd like:**

Make Chaos Mesh run with istio

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

TBD

**Comment by Yisaer** [comment]
I'm familiar with Istio and other ServiceMesh products. Can I take this work?

**Comment by zhouqiang-cl** [comment]
Of cause, thank you

**Comment by zhouqiang-cl** [comment]
> I'm familiar with Istio and other ServiceMesh products. Can I take this work?

Of cause, thank you

**Comment by Yisaer** [comment]
Before we make `chaos-mesh` run with `istio`, I think we should test the compatible between `istio` and `chaos-mesh`. 

ref:
https://github.com/pingcap/chaos-mesh/issues/146
