### ISSUE TITLE
proposal: add metrics for chaos CRD

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#148]
From @yeya24 's suggestion:
Chaos Mesh need some metrics to show how many CRDs it have for each kind of injection, we can use `gauge` metric.
If we have such metrics, it can display the history of CRDs and can be added to dashboard

**Comment by zhouqiang-cl** [comment]
@cwen0 @mahjonp @YangKeao what about your opinion

**Comment by cwen0** [comment]
This function may be combined with dashboard, because we also need to get these message in dashboard and show them on dashboard. @zhouqiang-cl

**Comment by mahjonp** [comment]
LGTM, we need a metrics HTTP handler on chaos-engine, no matter how to show these metrics.

**Comment by zhouqiang-cl** [comment]
> This function may be combined with dashboard, because we also need to get these message in dashboard and show them on dashboard. @zhouqiang-cl

Tomorrow @YangKeao will take a look

**Comment by YangKeao** [comment]
Maybe we could add an argument to specify the prometheus address we use (for both recording controller-manager's metric and show on dashboard) just like TiKV. `Inc` and `Dec` is very easy to manager in `controller-manager`.

**Comment by zhouqiang-cl** [comment]
> Maybe we could add an argument to specify the prometheus address we use (for both recording controller-manager's metric and show on dashboard) just like TiKV. `Inc` and `Dec` is very easy to manager in `controller-manager`.

@yeya24 how about your opinion

**Comment by yeya24** [comment]
I don't think it is a good pattern to use pushgateway like tikv. A http /metrics endpoint is good enough.

**Comment by yeya24** [comment]
I think I can contribute to this as well since I am familiar with it.

**Comment by zhouqiang-cl** [comment]
> I am not quite familiar the way Tikv use. Do you mean using pushgateway? I don't think it is a good pattern. A http /metrics endpoint is good enough.

I think pushgateway is not fit for us, Now tikv already remove pushgateway too

**Comment by yeya24** [comment]
Metrics for Chaos-daemon are necessary as well. Several steps we need to implement that.

1. Add a HTTP endpoint `/metrics` to chaos-daemon, expose some basic metrics first. Like go and process metrics
2. Add Grpc metrics, we can use https://github.com/grpc-ecosystem/go-grpc-prometheus
3. Add other custom metrics

**Comment by zhouqiang-cl** [comment]
> 1. metrics

Agree with @yeya24 , And maybe we should start a prometheus for Chaos Mesh(not using the system)

**Comment by zhouqiang-cl** [comment]
@yeya24 will you help to add metrics for chaos CRDs? thank you very much

**Comment by yeya24** [comment]
Yes, but maybe later. I have checked the logic in the inner reconciling, but currently, I don't come up with a good, general way for the existing CRD controllers,  since each one has its own logic.

**Comment by zhouqiang-cl** [comment]
@yeya24 take your time 😝

**Comment by yeya24** [comment]
Still valid. But kind of low priority.
