### ISSUE TITLE
refine `get started on your local machine` section in readme

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#150]
## Feature Request
The [get started on your local machine](https://github.com/pingcap/chaos-mesh#get-started-on-your-local-machine) section in  readme is not very friendly. we need to improve it. 

**Describe the feature you'd like:**

The mode `kind` is not very fault-tolerant, lack of necessary error handling. Maybe we can make `minikube` as primary mode for local machine and `kind` as secondary mode

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

None

**Comment by cwen0** [comment]
fix in pr #217
