### ISSUE TITLE
Write a tutorial to use Chaos Mesh to test a simple program

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#153]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Write a very simple program and use chaos mesh test it

**Describe the feature you'd like:**

- write a simple program
- use chaos mesh test it
- write the tutorial about the program and how to use chaos mesh to test it

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

None

**Comment by oraluben** [comment]
I feel that this tutorial should also have a dashboard to do some visualization.
Ref #170

**Comment by zhouqiang-cl** [comment]
> I feel that this tutorial should also have a dashboard to do some visualization.
> Ref #170

yichen，this days we are design for dashboard and write a web application demo for it、the web application is ready、the design will come out in few days
