### ISSUE TITLE
make commands more clear in readme

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#155]
## Feature Request

**Is your feature request related to a problem? Please describe:**

- refine readme: follow the step by step commands,  just copy and past can start the whole cluster with chaos

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by oraluben** [comment]
This will be partially resolved by [#247](https://github.com/pingcap/chaos-mesh/pull/247)

**Comment by zhouqiang-cl** [comment]
> This will be partially resolved by [#247](https://github.com/pingcap/chaos-mesh/pull/247)

yes yes
