### ISSUE TITLE
what about using cni/plugins/ns instead of nsenter?

### ISSUE THREAD

**Issue by yeya24** [pingcap/chaos-mesh#159]
## Question
https://github.com/containernetworking/plugins/blob/master/pkg/ns/README.md has basic network ns utilities. Is it better to use it instead of using cmd with nsenter? 

With that pkg, we can solve https://github.com/pingcap/chaos-mesh/issues/64 as well.

But with that pkg, the code will become more complicated than the current implementation.

**Comment by zhouqiang-cl** [comment]
@YangKeao @cwen0  PTAL

**Comment by YangKeao** [comment]
@yeya24 Thanks for your suggestion :beers:  . In the previous version of chaos-mesh, we `setns` through `github.com/vishvananda/netns` pkg. In #31, `chaos-mesh` turned to use `nsenter` to enter a network namespace.

According to the [document](https://github.com/containernetworking/plugins/blob/master/pkg/ns/README.md) you have shared with us, after go 1.10 we can work with network namespace in go safely. 

I will take a look at what changes have been made by go 1.10 and how it solved [problems issued by weavenet](https://www.weave.works/blog/linux-namespaces-and-go-don-t-mix).

Controling networkspace in a "programmable" way is definitely better than using `nsenter` and the limitation (require go >= 1.10) is surely acceptable. I will work on this right after Spring Festival (or would you contribute to `chaos-mesh` :smile: ? )

**Comment by yeya24** [comment]
@YangKeao  Thanks. To be honest, I haven't noticed that network ns leakage before. I am not sure whether this package is safe enough, though it is used in CNI. I think I can investigate more and test locally first for this plan.
