### ISSUE TITLE
Add event to record each chaos action

### ISSUE THREAD

**Issue by Yisaer** [pingcap/chaos-mesh#162]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, we didn't have any places to show the chaos actions which have been done after we apply the chaos api. I think it might be important for users to know the effect caused by chaos-mesh by each chaos api component.

**Describe the feature you'd like:**

For example, after I apply the `PodChaos` api, I could get the information by
```bash
kubectl describe pod-chaos xx 
```
And I can find the information for when and which pod the pod-chaos effected in events.

**Comment by zhouqiang-cl** [comment]
great idea

**Comment by zhouqiang-cl** [comment]
Also need show how many times it trigger, the trigger time and some description message

**Comment by AngleNet** [comment]
HI. Is there anyone working on this issure ? If not, I am willing to contribute. @Yisaer @zhouqiang-cl

**Comment by Yisaer** [comment]
@AngleNet  Thanks, feel free to work on this issue.

**Comment by AngleNet** [comment]
Any implementation hints for this issue ? @Yisaer @zhouqiang-cl

**Comment by Yisaer** [comment]
@AngleNet  ChaosMesh is built based on the KubeBuilder.  Here is the document about the `Events` in KubeBuilder. I think this would help you.

https://book-v1.book.kubebuilder.io/beyond_basics/creating_events.html

**Comment by zhouqiang-cl** [comment]
@AngleNet Did things goes well, or did you need more docs?  no rush

**Comment by AngleNet** [comment]
I'm still working on it. It is a little bit busy for now. I will try my best to open the PR in this week. I will let you know if I need more help. Thanks ~~~

**Comment by zhouqiang-cl** [comment]
That's OK. thank you. take your time

**Comment by Yisaer** [comment]
@AngleNet You don't have to add event in all controllers. Only create the event recorder in Controller would also helpful for us.
Then the developers could add events in each controller in parallel.

**Comment by AngleNet** [comment]
Alright. Will file a PR only for event recorders.

**Comment by zhouqiang-cl** [comment]
It solved by @AngleNet . I will close this issue
