### ISSUE TITLE
Supports customized dashboard

### ISSUE THREAD

**Issue by yeya24** [pingcap/chaos-mesh#170]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

The current chaos-dashboard is just a React page with embedded Grafana dashboard using iframe. It is quite inconvenient to customize my dashboards. The only way I can come up with now is to re-build the docker image.

Actually Grafana supports some APIs to manage dashboards. So it would be nice to support this functionality in chaos-dashboard, which will create a dashboard in backend Grafana and render it in the chaos-dashboard itself. But this feature may require a real backend in chaos-dashboard

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zhouqiang-cl** [comment]
Yes，we need a new dashboard to support cncf‘s project，and make it more flexible ，customized is needed，could you write a proposal for it？thank you very much

**Comment by cwen0** [comment]
@yeya24 looking forward to your proposal, In fact, we really want to rewrite the current dashboard with TypeScript. 😂It's just my personal idea.

**Comment by yeya24** [comment]
> @yeya24 looking forward to your proposal, In fact, we really want to rewrite the current dashboard with TypeScript. 😂It's just my personal idea.

I am busy with some other stuff so I don't think I have time to write it recently. And to be honest, I am not sure how to design it, maybe we need more discussioin
