### ISSUE TITLE
Make scheduler and duration optional for apis

### ISSUE THREAD

**Issue by Yisaer** [pingcap/chaos-mesh#171]
## Feature Request

**Is your feature request related to a problem? Please describe:**

As #72 suggested, currently `scheduler` and `duration` necessary in `chaos` API is not friendly for users. So we decided to make `scheduler` and duration `optional` for each kind of `chaos` API.

For the current `chaos` APIs, I would like to separate them into 3 kinds to talk about by different user cases.

#### scheduler chaos
For `network chaos`/`Io Chaos`/`pod-failure`/`pod-kill`, if `scheduler` and `duration` is defined, the chaos action would perform periodicity for a long term `chaos` testing.

#### duration chaos
For `network chaos`/`Io chaos`/`pod failure`, if `scheduler` and `duration` is omitted, the chaos action would perform immediately when `chaos-manager` received it. When the `chaos` API objects was deleted, the `chaos-manager` would recover it as previous which would be easy for users to observe the chaos action.

#### trigger chaos
For `pod-kill`, we would like to set up an HTTP server (or other protocols) to consume the request for trigger the `pod-kill` for each single time.

**Describe alternatives you've considered:**

First, we need to change the `chaos` API definitions to make `scheduler` and `duration` optional.
After this, we can make `IO Chaos`, `network chaos`, `pod chaos` to support this feature in parallel.

Considering `scheduler` and `duration` should be defined or omitted at the same time, we also need a validation admission webhook to validate the `chaos` API when it was created or updated.

**Comment by Yisaer** [comment]
cc @zhouqiang-cl @cwen0 @YangKeao

**Comment by zhouqiang-cl** [comment]
Did we need made duration chaos also triggerable, such as a HTTP API trigger duration chaos, another HTTP API stop the chaos

restLGTM

**Comment by Yisaer** [comment]
> Did we need made duration chaos also triggerable, such as a HTTP API trigger duration chaos, another HTTP API stop the chaos
> 
> restLGTM

Not suggested, it would be much complex for users and developers if we mix both `trigger chaos` and `duration chaos`.

**Comment by zhouqiang-cl** [comment]
> chaos

then LGTM

**Comment by cwen0** [comment]
@Yisaer Good job,  I think `HTTP API ` is not necessary at present, first, we can try to implement ` immediate job` and we can try to extend the scheduler structure, such as implementing other trigger methods in the future, such as callback.

**Comment by Yisaer** [comment]
@cwen0  I agreed. Currently, duration chaos is more important.

**Comment by zhouqiang-cl** [comment]
@Yisaer  The pr #172 is a great milestone, since it have been merged. could you update readme.

**Comment by Yisaer** [comment]
@zhouqiang-cl  #172 is the first step for this feature, I think we can update the `README.md` after 
 finishing the rest logic in controller for each kind of duration chaos.

**Comment by zhouqiang-cl** [comment]
@Yisaer Got

**Comment by Yisaer** [comment]
I think this issue should be reopened to track the validation admission webhook .

**Comment by zhouqiang-cl** [comment]
> I think this issue should be reopened to track the validation admission webhook .

Maybe we should change the title?
