### ISSUE TITLE
Check CRD in CI 

### ISSUE THREAD

**Issue by Yisaer** [pingcap/chaos-mesh#173]
## Bug Report
I found that there existed difference between origin `crd` files and the `crd` files auto-generated by the API spec after I execute the `make manifests` in master branch (7bccfb1). I think we need to add checking `crd` in CI to make sure the `crd` would be latest.

**What did you do?**

**What did you expect to see?**
After I execute the `make manifests`, there won't be any difference.

**What did you see instead?**
After I execute the `make manifests`, there are some difference between the origin and the newly generated.

**Comment by Yisaer** [comment]
And the executing `make yaml`  also had the same problem.

**Comment by Yisaer** [comment]
cc @zhouqiang-cl  @cwen0  @mahjonp

**Comment by zhouqiang-cl** [comment]
@YangKeao PTAL

**Comment by YangKeao** [comment]
CI will check this now :rocket: 

CI will check whether there are any difference after `make fmt` and `make yaml`. Difference in `go.mod` and `go.sum` is ignored.
