### ISSUE TITLE
UCP: Use the namespace of chaos object as the namespace selector if the namespaces selector was unset

### ISSUE THREAD

**Issue by mahjonp** [pingcap/chaos-mesh#178]
## Description

At present, the organization of chaos crd and the system under test(SUT) is not very friendly. 

Refer to documents of chaos-mesh, crds are placed in the [chaos-testing](https://github.com/pingcap/chaos-mesh/blob/4613209daea617519adb00d6ea596b270874b906/examples/pod-failure-example.yaml#L5) namespace, There are currently 2 problems:
* There is currently no intuitive way to see which chaos rules exist on one SUT if chaos rule was not placed in the same namespace with SUT(Components of system under test are usually organized in same namespace).
* When the SUT is destroyed, the corresponding chaos crd may still exist under the chaos-testing namespace, and it will take effect again the next time when another system with the same namespace name is created.

Current design enable one chaos rule take effect on different namespaces, but that's not necessary and it's better to bind a chaos rule with only one namespace IMO.

## Score 

* 300

## Mentor(s)

* @fewdan 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* Kubernetes

## Learning Materials

* [Development guide of chaos-mesh](https://github.com/pingcap/chaos-mesh/wiki/Development-Overview)

**Comment by YangKeao** [comment]
So, the requested feature is to automatically validate through webhook or something to ensure that chaos rules are placed in the same namespace with its objects? @mahjonp

**Comment by mahjonp** [comment]
> So, the requested feature is to automatically validate through webhook or something to ensure that chaos rules are placed in the same namespace with its objects? @mahjonp

Yeah, that's what I mean.

**Comment by cwen0** [comment]
> So, the requested feature is to automatically validate through webhook or something to ensure that chaos rules are placed in the same namespace with its objects? @mahjonp 

I think this requirement is a bit strict because it is possible that the chaos objects involves multiple namespaces.

**Comment by cwen0** [comment]
About this issue,  I think that the namespace selector should be kept in the selector, but if the namespace selector is not set, the namespace of the CRD object is used for filtering pods by default.

**Comment by cwen0** [comment]
List some points to note: 

* the [pods](https://github.com/pingcap/chaos-mesh/blob/master/api/v1alpha1/common_types.go#L36) field in the selector, this field is used to specify certain specific pods. If the `pods` field was sed, we should ignore this default namespace. 
* I think we should remove the namespace field in all chaos [examples](https://github.com/pingcap/chaos-mesh/tree/master/examples) because we need to guide the user to set the namespace to the namespace of application 

@Gallardot

**Comment by Gallardot** [comment]
@cwen0 
I got it, please assigned to me.

**Comment by zhouqiang-cl** [comment]
@Gallardot now we have an activity. refer is here https://mp.weixin.qq.com/s/VNtLhbOIJaAX2dEmjt8d5w
you can check it and register. When the pr is merged, you will get a score which have many usage

**Comment by Gallardot** [comment]
thank you @zhouqiang-cl .  I will take a look.
