### ISSUE TITLE
UCP: Add protect policy to prevent the injected system from being unintentionally damaged

### ISSUE THREAD

**Issue by mahjonp** [pingcap/chaos-mesh#179]
## Description

For example, after you inject ‘pod-kill’, the target pods are killed but they cannot return to the ‘Running’ state in time due to some reasons. Yet the pod-killing action continues. So all the pods might be under unhealthy status after a while and the overall system is somehow disrupted.

Add protection mechanism to avoid similar situations for pod-kill or other chaos crds: 
- block injection when the number of Running pod is below at a certain percentage rate.
- extend `selector`, e.g use regex to filter target pods.

Or we can extend `mode` methods, add `uniqueOne`.

## Score 

* 936.1

## Mentor(s)

* @fewdan 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* Kubernetes

## Learning Materials

* [Development guide of chaos-mesh](https://github.com/pingcap/chaos-mesh/wiki/Development-Overview)

**Comment by cwen0** [comment]
@mahjonp I agree with your opinion and this required feature is useful for the user.
