### ISSUE TITLE
UCP : Use a real image for fake image

### ISSUE THREAD

**Issue by YangKeao** [pingcap/chaos-mesh#189]
## Description

Currently, in pod-failure, we use a non-existing image (fake image) to update the current container image. In this way, we can make the pod unusable. 

But at the same time, there is a problem with this approach.  The restart time will accumulate to infinity. So we should use other methods. For example,  We can use `k8s.gcr.io/pause` or an empty image as a fake image.

## Score

50

## Mentor(s)

* @YangKeao 

Contact the mentors: #tidb-challenge-program channel in TiDB Community Slack Workspace

## Recommended Skills

* Golang
* Kubernetes

## Learning Materials

* [Development guide of chaos-mesh](https://github.com/pingcap/chaos-mesh/wiki/Development-Overview)

**Comment by zhouqiang-cl** [comment]
can it meet network issues

**Comment by you06** [comment]
@AngleNet try again please

**Comment by STRRL** [comment]
It will be better to use a image that with a certain name which exactly tell user "It is a pod-faliure action." 

Seeing `pause` in pod's spec makes a little confuse to me, then I realize it's cause by chaos-mesh.

**Comment by zhouqiang-cl** [comment]
@cwen0 @YangKeao What's your opinion

**Comment by fewdan** [comment]
@STRRL 
So you mean, we should make an image called "pod failure" or something similar?

**Comment by AngleNet** [comment]
Seems better to build a `pingcap/chaos-mesh/pause` image based on `gcr.io/pause` or something like that

**Comment by STRRL** [comment]
@fewdan Yes!

@AngleNet It's a easy way that just tag `pause` image then push to docker hub. But in my opinion, all-in-one docker image is not so elegant.

**Comment by AngleNet** [comment]
Yes ! I think could share the same prefix of `pingcap/chaos-mesh` ?
