### ISSUE TITLE
[Discuss] Should we retry when applying chaos or canceling chaos failed?

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#207]
In some situation, we may occur some kinds of error, such as network error.
When the chaos-operator 's communication with chaos-daemon is broken, there are some case list below:
- Chaos action create fail(means chaos not happend)
- Chaos action recover fail(means chaos action can not recover, alway in chaos)

How should we handle this situation. Did we need to using retry here. what about your opinion @cwen0 @YangKeao @mahjonp @Yisaer @yeya24

**Comment by AngleNet** [comment]
In my opinion, retry-pattern will increase complexity of the chaos implementation which leads more bugs. For a user, it could be difficult to add a satisfied chaos which complies with the retry-pattern agreed with project members liky you guys. For a chaos injection platform, availablity is less important. A chaos action should fail fast and detailly. Even futher, we could also provide recovery suggestions for a failed chaos action. Let users handle the failure, such as retrying or figuring out what's wrong with the chaos.

**Comment by zhouqiang-cl** [comment]
> In my opinion, retry-pattern will increase complexity of the chaos implementation which leads more bugs. For a user, it could be difficult to add a satisfied chaos which complies with the retry-pattern agreed with project members like you guys. For a chaos injection platform, availablity is less important. A chaos action should fail fast and detailly. Even futher, we could also provide recovery suggestions for a failed chaos action. Let users handle the failure, such as retrying or figuring out what's wrong with the chaos.

Agree !!! @cwen0 @Yisaer PTAL

**Comment by zhouqiang-cl** [comment]
@AngleNet Then maybe we just need add some metrics https://github.com/pingcap/chaos-mesh/pull/210 and show it in dashboard

**Comment by cwen0** [comment]
> > In my opinion, retry-pattern will increase complexity of the chaos implementation which leads more bugs. For a user, it could be difficult to add a satisfied chaos which complies with the retry-pattern agreed with project members like you guys. For a chaos injection platform, availablity is less important. A chaos action should fail fast and detailly. Even futher, we could also provide recovery suggestions for a failed chaos action. Let users handle the failure, such as retrying or figuring out what's wrong with the chaos.
> 
> Agree !!! @cwen0 @Yisaer PTAL

Yes, we can add a field to control the error handling method, such as setting a retry field, and if we do not use the retry method, if we encounter an error, we should also try to cancel chaos.

**Comment by zhouqiang-cl** [comment]
> Yes, we can add a field to control the error handling method, such as setting a retry field, and if we do not use the retry method, if we encounter an error, we should also try to cancel chaos.

@cwen0  can you file an issue about this?

**Comment by Yisaer** [comment]
Retrying reconciling is ok to me. But in my previous experience, If the reconciling is failed for the first time, it would possibly fail again in the next several times. 
I think it's better to set retrying threshold to limit the retrying count or interval duration and record it in the chaos API status and event and let the users to handle the problem.
@zhouqiang-cl @cwen0

**Comment by AngleNet** [comment]
> @AngleNet Then maybe we just need add some metrics #210 and show it in dashboard

Sorry for the delay. Yes. We should report the failure via Event and Dashboard both according to @Yisaer .

**Comment by AngleNet** [comment]
> Retrying reconciling is ok to me. But in my previous experience, If the reconciling is failed for the first time, it would possibly fail again in the next several times.
> I think it's better to set retrying threshold to limit the retrying count or interval duration and record it in the chaos API status and event and let the users to handle the problem which is both applied to the chaos action `Perform` and `Recover`.
> @zhouqiang-cl @cwen0

According to @Yisaer "If the reconciling is failed for the first time, it would possibly fail again in the next several times." If that happens a lot, the threshold could be useless since a good threshold is difficult to predict for a user. However, there maybe some failures that can be recovered by itself. These failures should be retried. Once we doubt about an auto-recoverable failure, we should discuss it case by case detailly. It can be time consuming. Only suggestions. @zhouqiang-cl @cwen0 @Yisaer

**Comment by zhouqiang-cl** [comment]
> According to @Yisaer "If the reconciling is failed for the first time, it would possibly fail again in the next several times." If that happens a lot, the threshold could be useless since a good threshold is difficult to predict for a user. However, there maybe some failures that can be recovered by itself. These failures should be retried. Once we doubt about an auto-recoverable failure, we should discuss it case by case detailly. It can be time consuming. Only suggestions. @zhouqiang-cl @cwen0 @Yisaer

sorry for late reply. LGTM, I think we can first report the failure via Event and Dashboard

**Comment by AngleNet** [comment]
Report to Event will be done along with #162 solved.
