### ISSUE TITLE
[Question] Does chaos-mesh plan to support chaos injection for other exection environments such as CPP or JVM ?

### ISSUE THREAD

**Issue by AngleNet** [pingcap/chaos-mesh#211]
There are also a large number of applications running on the dedicated OS. For those applications, K8s is to too heavy to get started. Maybe a simple chaos injection sandbox could be provided.

**Comment by zhouqiang-cl** [comment]
@AngleNet Chaos Mesh will not support non K8s environment. But we have write a document for command line chaos(for non K8s environment). That will come out in 2 or 3 days

**Comment by AngleNet** [comment]
Great !!!

**Comment by zhouqiang-cl** [comment]
@AngleNet The doc is here [Command line Chaos]( https://github.com/pingcap/tipocket/blob/master/doc/command_line_chaos.md)

**Comment by AngleNet** [comment]
Looks good. Can we put a reference on docs of this project.

**Comment by zhouqiang-cl** [comment]
> Looks good. Can we put a reference on docs of this project ?

Yes. of cause. I will add a link

**Comment by zhouqiang-cl** [comment]
@cwen0 Could you find a place to link this doc

**Comment by zhouqiang-cl** [comment]
@AngleNet already linked

**Comment by AngleNet** [comment]
Wonderful. Sorry for the delay.
