### ISSUE TITLE
proposal: Make dashboard show chaos-daemon's metrics

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#213]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When https://github.com/pingcap/chaos-mesh/pull/210 is merged, we can get the metrics of chaos daemon. I think we can show the metrics in Chaos Dashboard

**Describe the feature you'd like:**

Maybe just in grafana

**Describe alternatives you've considered:**

Write a dashboard like kubenetes's dashboard or just using grafana

**Teachability, Documentation, Adoption, Migration Strategy:**

None

**Comment by yeya24** [comment]
I think we need a Prometheus first

**Comment by zhouqiang-cl** [comment]
> I think we need a Prometheus first

Of cause!!!

**Comment by zhouqiang-cl** [comment]
@yeya24 will you take this issue?

**Comment by yeya24** [comment]
I can help add a Prometheus first.
But for Grafana, I am not sure about the current architecture. Seems we have one Grafana per namespace?

**Comment by zhouqiang-cl** [comment]
We inject each namespace a Grafana, which I thank we maybe need abandon later. I think we should also add a Grafana here. @YangKeao what's your opinion

**Comment by YangKeao** [comment]
If we need to present `chaos-daemon`'s metrics, I think we only need to add one grafana and prometheus (and related services) in chaos-mesh's namespace so that we can access it directly. 

As the current structure of `chaos-dashboard` is quite ugly and highly specialized for TiKV (which means it will be refactored definitely), it's not necessary to add this in `chaos-dashboard`. @zhouqiang-cl  @cwen0 How about you?

**Comment by zhouqiang-cl** [comment]
> If we need to present `chaos-daemon`'s metrics, I think we only need to add one grafana and prometheus (and related services) in chaos-mesh's namespace so that we can access it directly.

Yes. I agree

**Comment by zhouqiang-cl** [comment]
> As the current structure of `chaos-dashboard` is quite ugly and highly specialized for TiKV (which means it will be refactored definitely), it's not necessary to add this in `chaos-dashboard`.

I agree too. `chaos-dashboard` need refine later
