### ISSUE TITLE
[Feature Request] Add simple IOChaos example with mysql

### ISSUE THREAD

**Issue by Yisaer** [pingcap/chaos-mesh#216]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

I think adding a simple IOChaos example with mysql (or other common databases / file system) would be user-friendly and helpful for community users to try ChaosMesh. Current example with `Tikv` for users is to complex to have a first quick trial.

**Comment by zhouqiang-cl** [comment]
Make Sense

**Comment by Yisaer** [comment]
And this is also necessary to #214 because of lack of method to test.

**Comment by yeya24** [comment]
I can take this one if no one is currently working on it.
I plan to add:
1. mysql iochaos
2. prometheus iochaos

**Comment by zhouqiang-cl** [comment]
> I can take this one if no one is currently working on it.
> I plan to add:

thank you very much😄
