### ISSUE TITLE
UCP: Make deleting chaos objects more elegant and not blocked by finalizers

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#227]
## Description

At present, we use finalizers to prevent chaos action residues when a chaos object is deleted. Why do chaos action residues occur? Under normal circumstances, after we apply chaos successfully, we will add a [finalizer](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers) to the corresponding chaos object. When we execute delete action, we will recover the current chaos behavior according to the finalizers inserted before. Therefore, the following situations may be occurring:

* The apply action failed, but I didn't dare to ensure that it really failed. It may be caused by network failure, but we still record a finalizer. 
* The cancel action failed, but it is also not guaranteed whether it has actually been canceled

In both cases, the delete chaos operation may be blocked. You need to manually confirm the operations recorded in finalizers and perform the manual cleanup. This behavior will confuse users and is not very friendly to users who need automated operations.

The purpose of this task is to solve this problem. Here are some ideas:

* For more detailed error judgments, we do not record the finalizer when it is determined that the real apply does not take effect, and the same cancel object determines that there is no chaos behavior to delete the finalizer
* Adding an option to control can forcibly delete and ignore the error when canceling

## Score 

* 600

## Mentor(s)
* @cwen0 

## Recommended Skills

* Golang
* [Kubernetes](https://kubernetes.io/)

## Learning Materials

* [Development guide of chaos-mesh](https://github.com/pingcap/chaos-mesh/wiki/Development-Overview) 
* [CRD](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/)
* [Finalizers](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers)

**Comment by yujunz** [comment]
> * Adding an option to control can forcibly delete and ignore the error when canceling

This is needed anyway. Could you elaborate about how to implement it?

Not quite familiar with existing code at the moment, but I can probably take this task given necessary guidance. @cwen0

**Comment by cwen0** [comment]
@yujunz I am very happy to help resolve this issue. I will share some thoughts on this issue later.

**Comment by cwen0** [comment]
@yujunz I have two thoughts on this issue. 

> * For more detailed error judgments, we do not record the finalizer when it is determined that the real apply does not take effect, and the same cancel object determines that there is no chaos behavior to delete the finalizer
> * Adding an option to control can forcibly delete and ignore the error when canceling  

About the first point, you can find the record finalizer logic in controllers, such as NetworkChaos [types.go](https://github.com/pingcap/chaos-mesh/blob/master/controllers/networkchaos/netem/types.go#L224), and we will add this finalizer before applying the chaos action. I suggest that we only record the finalizer when the action was applied successfully. In addition, when to cancel chaos action, we should check the target pod status, if the pod was destroyed, we should allow removing the finalizer. https://github.com/pingcap/chaos-mesh/blob/master/controllers/networkchaos/netem/types.go#L166

The second point, we can add a field for each chaos object, such as NetworkChaos [network_types.go](https://github.com/pingcap/chaos-mesh/blob/master/api/v1alpha1/networkchaos_types.go#L93)

```
type NetworkChaosSpec struct {
... 
CleanupEnsure bool 
}
```

If the value `CleanupEnsure` is true and the cancel action failed, the delete chaos operation may be blocked. You need to manually confirm the operations recorded in finalizers and perform the manual cleanup. Otherwise, we will ignore the failure. We can check the `CleanupEnsure` when the cancel the chaos action at https://github.com/pingcap/chaos-mesh/blob/master/controllers/networkchaos/netem/types.go#L165. 

In addition, I think we can split multi pr to solve this issue.

**Comment by cwen0** [comment]
@yujunz Hi, Currently, we are preparing Chaos Mesh-for CNCF Sandbox entry. https://github.com/cncf/toc/pull/367. At present, we are preparing the slide which requires some contributor-related information.  Would you mind tell us what company are you from?

**Comment by yujunz** [comment]
> In addition, I think we can split multi pr to solve this issue.

Agree. I may spend some time to get familiar with existing development process first.

Is https://github.com/pingcap/chaos-mesh/wiki/Development-Overview where I should get started?

**Comment by cwen0** [comment]
> > In addition, I think we can split multi pr to solve this issue.
> 
> Agree. I may spend some time to get familiar with existing development process first.
> 
> Is https://github.com/pingcap/chaos-mesh/wiki/Development-Overview where I should get started?

Yes, In addition, this tutorial maybe helps you. https://yisaer.gitbook.io/chaos-mesh-contributing-tutorials/

**Comment by cwen0** [comment]
@yujunz Is there any new progress on this issue? need any help?

**Comment by yujunz** [comment]
Not making much progress on this issue due to some other urgent project.

But I do have a [deep dive to the code](https://docs.google.com/presentation/d/1cIo2P7QgAcJk1rOfcZASmfDppNc5DY9nmVqVdiQmdY4/edit?usp=sharing) and get the [hello world chaos](https://github.com/yujunz/chaos-mesh/tree/hello-world) working now.

I will go over your thoughts and consider how to implement it. Will let you know if I need more help.

**Comment by yujunz** [comment]
@cwen0 
A draft implementation is available for review. Not tested yet.

**Comment by cwen0** [comment]
@yujunz Yes, this is a good idea, but I may prefer to use annotation to force cleanup.

**Comment by yujunz** [comment]
> * For more detailed error judgments, we do not record the finalizer when it is determined that the real apply does not take effect, and the same cancel object determines that there is no chaos behavior to delete the finalizer

Do you have concrete issues for this point? @cwen0 

> * Adding an option to control can forcibly delete and ignore the error when canceling

This is done.

**Comment by yeya24** [comment]
This is done. Close now.
