### ISSUE TITLE
Support cert-manager for certificate management

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#237]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Some users may provide their own certificates, it's better to use cert-manager to manage the certificates. It's more mature and has many features we need. On the other hand, cert-manager may be the default in the K8s world now.

**Describe the feature you'd like:**

Integrate [cert-manager](https://github.com/jetstack/cert-manager)  for certificate management.

**Comment by Gallardot** [comment]
I'd like to try this issue.Currently, a post-install hook is used to perform the create-cert job and install mutatingwebhook job.I think we can use an option to use cert-manager to do the same thing.

**Comment by cwen0** [comment]
@Gallardot Thanks, feel free to work on this issue. I agree with your option.

**Comment by zhouqiang-cl** [comment]
@Gallardot thank you

**Comment by Gallardot** [comment]
I'm working on this issue. But I have some questions.

"Integrate" cert-manager or "Use" cert-manager?

For integration, the charts of chaos-mesh need to dependencies on the charts of cert-manager. If we install chaos-mesh, the cert-manager will be installed synchronously.

If we just use it, I think we just need to have some documentation on how to install cert-manager, such as the official cert-manager documentation, or we can provide some installation steps.

> On the other hand, cert-manager may be the default in the K8s world now.



I think we just 'use' it.Use cert-manager is just an option. I will use 'Issuer' and 'Certificate' of cert-manager on this issue.And I will provide some documentation about how to install cert-manager.

**Comment by cwen0** [comment]
> I'm working on this issue. But I have some questions.
> 
> "Integrate" cert-manager or "Use" cert-manager?
> 
> For integration, the charts of chaos-mesh need to dependencies on the charts of cert-manager. If we install chaos-mesh, the cert-manager will be installed synchronously.
> 
> If we just use it, I think we just need to have some documentation on how to install cert-manager, such as the official cert-manager documentation, or we can provide some installation steps.
> 
> > On the other hand, cert-manager may be the default in the K8s world now.
> 
> I think we just 'use' it.Use cert-manager is just an option. I will use 'Issuer' and 'Certificate' of cert-manager on this issue.And I will provide some documentation about how to install cert-manager.

I also think we just `use` it. When Chaos Mesh support to use ` cert-manager`, the document about how to use `cert-manager`  does need to be added and we can add a link about how to install cert-manager in this doc.

**Comment by cwen0** [comment]
@Gallardot How is this task going? 😊

**Comment by Gallardot** [comment]
@cwen0  Almost done.  I’m writing the docs for this issue. I will create a PR later.

**Comment by zhouqiang-cl** [comment]
@Gallardot thank you for your big contribution. Since the pr is closed. I will close this issue
