### ISSUE TITLE
Enable pprof in all conponents of Chaos Mesh

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#238]
## Feature Request

**Is your feature request related to a problem? Please describe:**
 
Sometimes we need to locate some Chaos Mesh issue, such as performance, memory leaks, etc. I think `pprof` can help us. So I recommend enabling `pprof` in all components of chaos-mesh

**Comment by yeya24** [comment]
I think I can take this one. But may I ask what do you mean by `all components`? What does it include? Does it include `chaos-dashboard` and `chaos-fs`?

**Comment by zhouqiang-cl** [comment]
@yeya24 I think manager and daemon is enough

**Comment by yeya24** [comment]
In controller-manager, do we want to use the metrics port for pprof as well?

**Comment by zhouqiang-cl** [comment]
> In controller-manager, do we need to use the metrics port for pprof as well?

I think we can
