### ISSUE TITLE
Show the chaos result on the status field of Chaos Object 

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#240]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I think we should be able to get the experimental results from the status of chaos object. Currently, we just record very little information on the status field and can't show the current experimental results well.  I think we should refactor the status filed on each chaos object.  

**Describe the feature you'd like:**
 

For different chaos objects, the definition of this field may be different. We should be able to directly judge the current status of the chaos through this field, such as whether the chaos object is running normally？Is the previous experiment normal?  what are the latest experimental objects, When did it start? When will it end？etc...

**Comment by psinghal20** [comment]
Hey @cwen0 @zhouqiang-cl, I would love to take a stab at this issue, if no is working on it. I am new to this project and the Kubernetes ecosystem. Some tips on how to proceed with this issue will help a lot. Thanks!

**Comment by zhouqiang-cl** [comment]
@psinghal20 Now no one is working on it, I will assign it to you. thank you very much
@cwen0 Please provide some tips

**Comment by cwen0** [comment]
@psinghal20 I have an idea about this issue, design a CRD object to save the chaotic results instead of the state of the chaotic object? There are some advantages to doing this:

* Avoid updating the object itself multiple times, I think we can just treat the crd object itself as a configuration file
* Easier to check experimental results and expand easily
*It is more convenient to combine with the chaos dashboard

@YangKeao @Yisaer @zhouqiang-cl PTAL

**Comment by cwen0** [comment]
@psinghal20 After careful consideration, I felt that the benefit of creating a CRD object separately is not great,  so I will close this issue.
