### ISSUE TITLE
Network Chaos support  groups of pods from one another

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#243]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When we have multi IDC, then we need support groups of pods from one another

**Describe the feature you'd like:**

Such as there are two group of pods. 
```
group1 = {podA, podB, podC}
group2 = {podD, podE, podF}
```
Then the latency from any pod of group1 to group2 is 100ms

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

None

**Comment by hoang-tranviet** [comment]
Hello,
Thanks for the proposal, I am interested in this feature.
Do you think that we could reuse some part of partition chaos, or it is better to implement it completely new from scratch?

**Comment by YangKeao** [comment]
I think this issue is related to #295
