### ISSUE TITLE
After delete configmap, still inject sidecar.

### ISSUE THREAD

**Issue by Gallardot** [pingcap/chaos-mesh#259]
## Bug Report

**What version of Kubernetes are you using?**

v1.17.2

**What did you do?**

After install chaos-mesh on chaos-testing namespace
I use the etcd example for the iochaos.

```

kubectl label ns chaos-testing admission-webhook=enabled
kubectl annotate ns chaos-testing admission-webhook.pingcap.com/init-request=chaosfs-etcd

cd examples/etcd
kubectl create -f etcd-configmap.yaml
kubectl create -f etcd-iochaos.yaml
kubectl create -f etcd.yaml
```

We can inject sidecar to the etcd's pod. So far so good,but

```
# delete iochaos and configmap
kubectl delete -f etcd-iochaos.yaml
kubectl delete -f etcd-configmap.yaml

# restart the ectd deployment
kubectl rollout restart deploy etcd
```

After restart the ectd deployment,I find that we still inject sidecar to the etcd's pod. But why？

```
kubectl label ns chaos-testing admission-webhook=disable --overwrite

kubectl rollout restart deploy etcd
```
After this，we can not  inject sidecar to the etcd's pod. It's ok.

**What did you expect to see?**
After delete configmap, we should not inject sidecar to the etcd's pod.

**What did you see instead?**
After delete configmap, we still inject sidecar to the etcd's pod.

================

Of course, this may not be a bug. Because of the design.

I find that the webhook will cached the configmap.But why we need to cached this?  I can't find the relevant documents.

https://github.com/pingcap/chaos-mesh/blob/69fec19a91bb5d1cdf78492fbcb8b8b461cefbff/pkg/webhook/config/config.go#L105

And there is nothing to deal with deleting configmap.

https://github.com/pingcap/chaos-mesh/blob/9705112c60f0721c64e4730df62b40d7178edb4f/cmd/controller-manager/main.go#L232-L235

https://github.com/pingcap/chaos-mesh/blob/69fec19a91bb5d1cdf78492fbcb8b8b461cefbff/pkg/webhook/config/config.go#L229-L237

**Comment by cwen0** [comment]
@Gallardot Thanks for your feedback. Sometimes, the user may delete the ConfigMap by mistake, but this configmap is still used by some experiments, which may cause many experiments to fail. And we has provided a switch to control the chaos experiment. So I think removing ConfigMap should not be used as a switch to control whether IOChaos is injected

**Comment by Gallardot** [comment]
@cwen0  Thank you for reply. The switch to control whether sidecar is injected is the admission-webhook label of namespace.   I got it.
