### ISSUE TITLE
[Proposal] A New Design for Control Layer Controller

### ISSUE THREAD

**Issue by Yisaer** [pingcap/chaos-mesh#269]
During my work in realizing [common chaos controller](https://github.com/pingcap/chaos-mesh/pull/175) and supporting [pod/container-kill controlled by twophase controller](https://github.com/pingcap/chaos-mesh/pull/244), I found that the `common chaos ` controller and `twophase` controller have lots of redundant code and their logic is kind of simliar.

Let's take a look on the current control layer structure.
For `twophase controller`:
```golang
if chaos.IsDeleted() {
	Recover logic
} else if !chaos.GetNextRecover().IsZero() && chaos.GetNextRecover().Before(now) {
	Recover logic
} else if chaos.GetNextStart().Before(now) {
	Perform logic
} else {
	Requeue Logic
}
```
For `common controller`:
```golang
if chaos.IsDeleted() {
	Recover logic
} else {
	Perform logic
}
```
In the future, we are going to support the chaos with only `duration` property (kind like `Job`),
I guess its control layer controller layout might seems like below:
```golang
if chaos.IsDeleted() {
	Recover logic
} else if chaos.GetNextRecover().Before(now) {
	Recover logic
} else {
	Perform logic
}
```
Besides the similar controller logic, the `Perform` and `Recovery` logic here is also very similar with a little difference. I found that these similar control logic have the same 2 core problems: **When to start performing Chaos Action** and **When to recovery Chaos Action** which lead me to think a new design for the control layer controller structure.

In this design, I would like to introduce **2** controller to manage the lifecycle for the certain Chaos Kind instead of one previously. One of them would decide whether the chaos action should be performed and the other would decide whether the chaos action should be recoveried in each reconilation.

And the status for each Chaos Kind would only need 2 properties: **status** and **startTimestamp**. The **status** would have only 2 value (running/sleeping) to describe whether this chaos action is performing and the **startTimestamp** would record the starting timestamp for the current chaos action performing.

So let's take a example for a schedule chaos action with the following rule:

* For every chao action, the **status** would be **sleeping** and the **startTimestamp** would be 0 at the beginning.
* Performing Controller would only allow chaos action perform when their **status** is **sleeping**.
* If the Chaos action have schedule property, the Performing Controller would only allow it pass when its **startTimestamp** is below the current time for a necessary duration (calculated by its schedule propety)
* When the chaos action is permitted to be performing, its status should be changed into **running** and the start timestamp should be recorded.
* If they haven't, the performing controller would let it pass directly

* Recovery Controller would only allow chaos action recover when their **status** is **runnning**
* If the Chaos action have duration property, the Recovery Controller would only allow it pass when its **startTimestamp** is below the current time for a necessary duration (calculated by its duration propety)
* If they haven't, the Recovery Controller would reject it in this reconcilation.
* When the chaos action is recovered, its status should be changed into **sleeping**
* When the chaos action is deleted, the Recovery Controlled would recover its chaos action.

When a scheduler chaos is created with `every 5m` schedule and `3m` duration, its status would be changed as below:

current time (minute:second) | status | startTimestamp 
-|-|-
0:00 | sleeping | 0
0:01 | running | 0:01
3:01 | sleeping | 0:01
5:01 | running | 5:01

At 6:01s, if we edit this chaos action to omit its `schedule` and `duration` property to let it become a common chaos action, its status would be changed as below:

current time (minute:second) | status | startTimestamp 
-|-|-
6:01 | running | 5:01
7:01 | running | 5:01
8:01 | running | 5:01
9:01 | running | 5:01
10:01 | running | 5:01
11:01 | running | 5:01

And if we changed its `schedule` and `duration` property back on 12:00,its status would be changed as below:

current time (minute:second) | status | startTimestamp 
-|-|-
12:00 | running | 5:01
12:01 | sleeping | 5:01
12:02 | running | 12:02
15:02 | sleeping | 12:02
17:02 | running | 17:02

As you can see, in this double controller design, we manage the chao action by its status with the certain rules with nothing more redundent codes. And work for us to support the new feature of control layer controller would be to fulfill the rules and status instead of creating a new controller.

**Comment by YangKeao** [comment]
I think the complexity in current design doesn't come from status management. In your proposal's implementation, there will be two controllers. But in current implementation, we can also shrink to three controllers: `common`, `twophase` and a `job` controller, and the logic is much clearer.

As how we can do this, you can see code in [`chaos-dashboard`](https://github.com/pingcap/chaos-mesh/blob/master/cmd/chaos-dashboard/main.go) and [`collector`](https://github.com/pingcap/chaos-mesh/blob/master/pkg/collector/collector.go). We nearly have to register controllers for every different type (because we have to get resource according to its type), but we can share same logic.

So we have two choice now: follow the three controllers way or your two controllers way. The former one is more preferable for me as it's much clearer and easier to understand. 

But both of us agree that at least one of these two refactors should be done, doesn't it? :handshake:

**Comment by YangKeao** [comment]
If I didn't misunderstand your opinion, this issue can be split into two parts: 

1. Reduce the complicate/redundant controller logic.

2. Use new status management.

I think the first is much necessary and helpful for our development while the second one is not such urgent.

**Comment by Yisaer** [comment]
First, I agree that refactoring the controller layer logic is not urgent. 

Then, reducing the complexity and using new status management is not my point actually. Double Controller Design(in fact, 8, considering 4 kinds of chaos currently)  try to extend the schedule ability by rules on Permitting Performing and Permitting Recovering instead of using Specific controller ( schedule / common) on Specific logic. To support new schedule logic (like job), we have to add new controller.

Finally, this is just a guess of mine. I didn't expect that it would realize recently, but I think it's worth to be a choice once we found the controller layer logic is nearly out of control.
