### ISSUE TITLE
Load dashboard error

### ISSUE THREAD

**Issue by Gallardot** [pingcap/chaos-mesh#288]
## Bug Report

**What version of Kubernetes are you using?**

K8S v1.17.2
Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)

**What did you do?**

After install the chaos-mesh with dashboard

```
kubectl port-forward pod/chaos-dashboard-96655464b-dbqjq  8080:80
```
Open dashboard using Google Chrome

**What did you expect to see?**
Dashboard should be ok.

**What did you see instead?**

<img width="1196" alt="3C3B7271-74F6-453E-B2F8-FF404D70AFBD" src="https://user-images.githubusercontent.com/329265/75406632-e5bcdb00-594b-11ea-8151-480299c4103e.png">
<img width="579" alt="677298F8-544F-420E-A6D6-981641B2BA9E" src="https://user-images.githubusercontent.com/329265/75406649-f1100680-594b-11ea-858c-3892f07f363f.png">

**Comment by cwen0** [comment]
@YangKeao PTAL

**Comment by zhouqiang-cl** [comment]
@Gallardot could you try it again

**Comment by Gallardot** [comment]
thanks for @YangKeao . With the updated PR, and then it works!
