### ISSUE TITLE
We should remove the dependence on concrete chaos struct from validation pkg

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#291]
## Feature Request

In [validation](https://github.com/pingcap/chaos-mesh/tree/master/pkg/webhook/validation) pkg, the current implementation needs to use the concrete chaos struct ([L65-94](https://github.com/pingcap/chaos-mesh/blob/master/pkg/webhook/validation/validate.go#L65-L94)), which is very unfriendly for developing new chaos type.  

**Describe the feature you'd like:**

I think we only need to use the concrete chaos struct in [API](https://github.com/pingcap/chaos-mesh/tree/master/api/v1alpha1)  pkg and [controller](https://github.com/pingcap/chaos-mesh/tree/master/controllers) pkg. 

We can define a function in `API` pkg for `validation pkg`,  like: 

```
ParseChaosForValidation(data []bytes) Validation {
.... 
}
```

**Comment by Gallardot** [comment]
@cwen0 please assigned this to me.I will try this after the current work dones.I think it's the related work.

**Comment by cwen0** [comment]
fixed in #338
