### ISSUE TITLE
UCP: Support to set default value of chaos object by AdmissionWebhook

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#292]
## Description

When users apply a network chaos, some error may be reported: 

```
The NetworkChaos "network-delay-example" is invalid: []: Invalid value: map[string]interface {}{"spec":map[string]interface {}{"action":"delay", "delay":map[string]interface {}{"latency":"10ms"}, "duration":"30s", "mode":"one", "scheduler":map[string]interface {}{"cron":"@every 60s"}, "selector":map[string]interface {}{"labelSelectors":map[string]interface {}{"app":"web-show"}, "namespaces":[]interface {}{"default"}}}, "apiVersion":"pingcap.com/v1alpha1", "kind":"NetworkChaos", "metadata":map[string]interface {}{"namespace":"chaos-testing", "creationTimestamp":"2020-02-28T01:35:05Z", "annotations":map[string]interface {}{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"pingcap.com/v1alpha1\",\"kind\":\"NetworkChaos\",\"metadata\":{\"annotations\":{},\"name\":\"network-delay-example\",\"namespace\":\"chaos-testing\"},\"spec\":{\"action\":\"delay\",\"delay\":{\"latency\":\"10ms\"},\"duration\":\"30s\",\"mode\":\"one\",\"scheduler\":{\"cron\":\"@every 60s\"},\"selector\":{\"labelSelectors\":{\"app\":\"web-show\"},\"namespaces\":[\"default\"]}}}\n"}, "generation":1, "uid":"8bc122fd-59ca-11ea-a548-0242ac110002", "name":"network-delay-example"}}: validation failure list:
spec.delay.correlation in body is required
spec.delay.jitter in body is required
```

I think To avoid this, we may need `spec.delay.correlation` and `spec.delay.jitter` to be allowed to be unset in NetworkChaos and use a default value.

## Score 

* 604.6

## Mentor (s)

@cwen0 

## Recommended Skills

* Golang
* Kubernetes

## Learning Materials

* [Development guide of chaos-mesh](https://github.com/pingcap/chaos-mesh/wiki/Development-Overview)

**Comment by Gallardot** [comment]
+1
As the project evolves, we will have more and more CRDS and more and more fields.

May be we can use [Defaulting](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#defaulting) feature to support this feature request.But Defaulting  feature is alpha at v1.15 and stable at v1.17. It means that K8S V1.15 is the minimum version by chaos-mesh supported.
Of course, we can use MutatingWebhook to support this feature request too.
What 's your opinion?

**Comment by fewdan** [comment]
> +1
> As the project evolves, we will have more and more CRDS and more and more fields.
> 
> May be we can use [Defaulting](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#defaulting) feature to support this feature request.But Defaulting feature is alpha at v1.15 and stable at v1.17. It means that K8S V1.15 is the minimum version by chaos-mesh supported.
> Of course, we can use MutatingWebhook to support this feature request too.
> What 's your opinion?

@Gallardot However, the required environment for Chaos-Mesh is Kubernetes V1.12. If new features are introduced, you need to upgrade Kubernetes to V1.15.  This is equivalent to increasing environmental requirements. Can we implement the default value ourselves?

**Comment by Gallardot** [comment]
@fewdan 
Of course, we also can use MutatingWebhook to implement the default value feature.

**Comment by Gallardot** [comment]
@cwen0 please assigned this to me.I will try this after the current work dones.I think it's the related work.

**Comment by you06** [comment]
@Gallardot seems something wrong with network, and I also find that you've picker #178 successfully.
You can work on this task after submit PR for #178 or give up #178 start woking on this now. If there are any problems, call me for help. :)

**Comment by Gallardot** [comment]
@cwen0  
I need some help. What’s the default value for `spec.delay.correlation` and `spec.delay.jitter`

**Comment by cwen0** [comment]
@Gallardot I think we can keep unity with `tc` command and set them to "0". I don't sure, you can check the `tc` command to make sure it.

**Comment by Gallardot** [comment]
@cwen0 

reference to [netlink](https://github.com/vishvananda/netlink/blob/c79a4b7b40668c3f7867bf256b80b6b2dc65e58e/qdisc_linux.go#L15-L77) 、[tc](http://man7.org/linux/man-pages/man8/tc-netem.8.html)、[netem](https://wiki.linuxfoundation.org/networking/netem)

I think set them to "0" is OK.
