### ISSUE TITLE
UCP: Add a field in chaos object to allow to pause the current chaos experiment

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#294]
## Description

Sometimes, we want to stop the current chaos experiment to debug the application and the chaos experiment will be restart later. So we don't want to delete this chaos experiment.

In order to meet the above scenario, we want to add an option to each chaos object to temporarily pause the current experiment. we can directly use `kubectl patch` method to modify this field to start or stop the chaos experiment. 

If the chaos action has been applied successfully,  when we pause the chaos experiment, we should cancel the current chaos action. 

## Score 

* 936

## Mentor(s)
* @cwen0 

## Recommended Skills

* Golang
* Kubernetes 
* CRD

## Learning Materials

* [Development guide of chaos-mesh](https://github.com/pingcap/chaos-mesh/wiki/Development-Overview) 
* [CRD](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/)

**Comment by oraluben** [comment]
My understanding is that the pause action is like to stop (recover) the current chaos but not deleted, so it can be restarted later. If we want to restart the chaos, it's like to start a new chaos with same arguments.
So I'm adding a new field to chaos objects' spec like https://github.com/pingcap/chaos-mesh/pull/370/files#diff-3cc6826ef8417f43c87c3b8f98443246R172, and use https://github.com/pingcap/chaos-mesh/pull/370/files#diff-6ab9b4f7b52d5b6c41bbb79b9f3abf1dR2-R3 to patch the current chaos object. What do you think about this design? @cwen0
