### ISSUE TITLE
UCP: Test failed with proxy env

### ISSUE THREAD

**Issue by oraluben** [pingcap/chaos-mesh#299]
## Description
Run `make test` with env `HTTP_PROXY` and `HTTPS_PROXY`

• Failure [2.677 seconds]
webhook config watcher
/Users/yyc/GolandProjects/chaos-mesh/pkg/webhook/config/watcher/watcher_test.go:30
  Watch error
  /Users/yyc/GolandProjects/chaos-mesh/pkg/webhook/config/watcher/watcher_test.go:106
    should return unable to create watcher [It]
    /Users/yyc/GolandProjects/chaos-mesh/pkg/webhook/config/watcher/watcher_test.go:107

    Expected
        <string>: watcher channel has closed
    to contain substring
        <string>: unable to create watcher

    /Users/yyc/GolandProjects/chaos-mesh/pkg/webhook/config/watcher/watcher_test.go:118
Summarizing 1 Failure:

[Fail] webhook config watcher Watch error [It] should return unable to create watcher 
/Users/yyc/GolandProjects/chaos-mesh/pkg/webhook/config/watcher/watcher_test.go:118

Ran 13 of 13 Specs in 5.348 seconds
FAIL! -- 12 Passed | 1 Failed | 0 Pending | 0 Skipped

## Score 

* 50

## Mentor(s)
* @YangKeao 

## Recommended Skills

* Golang
* Kubernetes 
* CRD

**Comment by cwen0** [comment]
@fewdan PTAL

**Comment by oraluben** [comment]
With following patch `make test` with proxy env works well:

```
Index: Makefile
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- Makefile	(revision 4f2d73aa0f165a9d5241ecad85dbaadda5cbb14d)
+++ Makefile	(date 1582951908374)
@@ -48,7 +48,7 @@
 test: failpoint-enable generate fmt vet lint manifests test-utils
 	rm -rf cover.* cover
 	mkdir -p cover
-	$(GOTEST) ./api/... ./controllers/... ./pkg/... -coverprofile cover.out.tmp
+	env -u HTTP_PROXY env -u HTTPS_PROXY $(GOTEST) ./api/... ./controllers/... ./pkg/... -coverprofile cover.out.tmp
 	cat cover.out.tmp | grep -v "_generated.deepcopy.go" > cover.out
 	@$(FAILPOINT_DISABLE)
```

**Comment by YangKeao** [comment]
You could add `testhost` into `NO_PROXY` environment to solve it temporarily.

@cwen0 @fewdan Should we add `testhost` to `NO_PROXY` automatically?

**Comment by oraluben** [comment]
@YangKeao yes it worked.

I think that's a good idea because proxy is necessary to run test (`golang.org/x/tools/cmd/goimports`) in some environment.
