### ISSUE TITLE
proposal: use sidecar to pause the pod

### ISSUE THREAD

**Issue by siddontang** [pingcap/chaos-mesh#3]
Now we use a fake image to pause the pod, this is not elegant, I think we can use sidecar mechanism, maybe:

1. When we start the POD, using sidecar to inject an init container and start the init container.
2. Let the init container start the real container, so we can support pause.

This is just my guess, I don't think whether it can work or not, but we can have a try.

Or maybe we can find a better way?

**Comment by sftim** [comment]
You can use an [ephemeral container](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/) rather than a sidecar.

**Comment by YangKeao** [comment]
@sftim Do you have any suggestion on how to pause a pod with the help of ephemeral container?

BTW, the securityContext of ephemeral container [is not yet configurable](https://github.com/kubernetes/enhancements/issues/277#issuecomment-540952957)). It stops us from using ephemeral containers in IO and Network Chaos 😣.

**Comment by sftim** [comment]
With a shared process namespace `kill -STOP` simulates failure to progress; `kill -CONT` resumes. If you have the access to run it, you can use `ptrace()` with `PTRACE_ATTACH` as well.

`ptrace()` with `PTRACE_SEIZE` offers opportunities to trace processes and then later suspend them with `PTRACE_INTERRUPT`.

Otherwise (no shared namespace) there's not so much the container can do.

**Comment by zhouqiang-cl** [comment]
Thank you for you advise @sftim , @cwen0 PTAL

**Comment by zhouqiang-cl** [comment]
@sftim This feature is enabled in v1.17，I think we can make this as a option to support all kinds of signals later

**Comment by tennix** [comment]
> With a shared process namespace `kill -STOP` simulates failure to progress; `kill -CONT` resumes. If you have the access to run it, you can use `ptrace()` with `PTRACE_ATTACH` as well.
> 
> `ptrace()` with `PTRACE_SEIZE` offers opportunities to trace processes and then later suspend them with `PTRACE_INTERRUPT`.
> 
> Otherwise (no shared namespace) there's not so much the container can do.

When we stop the process by killing it with shared namespace, the container may restart again. I think what the proposal wants to achieve is making the container stop for some time. AFAIK, the fake image is the only way we can use now.

**Comment by YangKeao** [comment]
@tennix No. `kill -STOP` will not "kill" a process, but just send SIGSTOP signal. This inspired me another idea: we can use [`cgroup freezer`](https://www.kernel.org/doc/Documentation/cgroup-v1/freezer-subsystem.txt) to implement container pause (like docker does) in `chaos-daemon`!

Or simply use docker API to pause a container.

**Comment by YangKeao** [comment]
But `pod-failure` and `process-pause` maybe different kind of chaos. `pod-failure` means stop the pod and after several minutes it will restart. But `process-pause` will not stop and restart, but only fail to schedule. The difference is the "restart" process.

@cwen0 What's your opinion?

**Comment by cwen0** [comment]
yep, I also think that `pod-failure` and `process-pause` are different kinds of chaos. Some processes will handle some signals, so these two types of chaos also behave differently for the process. Next, we also need support `pod-pause`.

**Comment by zhouqiang-cl** [comment]
I will close this issue. If there are anything still need todo, then we can reopen it
