### ISSUE TITLE
still download K8S

### ISSUE THREAD

**Issue by fewdan** [pingcap/chaos-mesh#305]
## Bug Report

**What version of Kubernetes are you using?**

v1.16.0

**What did you do?**

"Kubectl" already exists in my computer, but when I execute "install.sh", I still need to download "kubectl".

**What did you expect to see?**

Do not need to download kubectl.

**What did you see instead?**

The script starts executing "curl" to download "kubectl".

Maybe it's because the "sort" version on my computer doesn't support "-V".

```
YIHAOFU-MB0:~ apple$ sort --version
sort (GNU coreutils) 5.93
Copyright (C) 2005 Free Software Foundation, Inc.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

Written by Mike Haertel and Paul Eggert.
YIHAOFU-MB0:~ apple$ sort -V
sort: invalid option -- V
Try `sort --help' for more information.
```

**Comment by cwen0** [comment]
this issue fixed in https://github.com/pingcap/chaos-mesh/pull/306, I will close it
