### ISSUE TITLE
Using `cilium` for network injection

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#307]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Maybe we can use [cilium](https://github.com/cilium/cilium) to extend our chaos action

**Describe the feature you'd like:**

Explore cilium and extend our chaos actions 

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

None

**Comment by AngleNet** [comment]
It seems cilium is a more promising way for operating and managing networks.

**Comment by zhouqiang-cl** [comment]
> It seems that cilium is a more promising way for operating and managing networks for us.

Yes. but it required bpf support

**Comment by AngleNet** [comment]
Is there a problem for adding bpf support? Forgive me. I don't get it.

**Comment by zhouqiang-cl** [comment]
Yes. It required a high kernel version(4.x). It seems now much server's kernel version is still 3.x

**Comment by AngleNet** [comment]
Make Cilium the default way to generate network chaos. When bpf is not available, fallback to netem ?

**Comment by zhouqiang-cl** [comment]
> Make Cilium the default way to generate network chaos. When bpf is not available, fallback to netem ?

Yes, Exactly what the issue want to display

**Comment by AngleNet** [comment]
Wow. Seems interesting. Could you share more details about how we extend the chaos action now ?

**Comment by zhouqiang-cl** [comment]
> Wow. Seems interesting. Could you share more details about how we extend the chaos action now ?

Sorry. I am still not sure about it now. It is still a suggestion and no proposal for it. Would you like to write a proposal for it(Maybe we also can found other use for `cilium`)

**Comment by AngleNet** [comment]
Yes. Let me try.
