### ISSUE TITLE
Why tidb-cluster-pd is pending and its “Events” in kubectl describe is none?

### ISSUE THREAD

**Issue by AndyXia23** [pingcap/chaos-mesh#317]
**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"$Format:%H$", GitTreeState:"archive", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

1. Install chaos mesh 
2. Deploy TiDB in Kubernetes Using kind

**What did you expect to see?**

The output of "kubectl get po -n tidb-admin -l app.kubernetes.io/name=tidb-cluster" should be that tidb-cluster-pd-0,  tidb-cluster-pd-1 and tidb-cluster-pd-2 are all running.

**What did you see instead?**

The output of "kubectl get po -n tidb-admin -l app.kubernetes.io/name=tidb-cluster" is that tidb-cluster-pd-0,  tidb-cluster-pd-1 and tidb-cluster-pd-2 are all pending. Another issue is that the "Events" in "kubectl describe  po -n tidb-admin -l app.kubernetes.io/name=tidb-cluster" is none.

**Comment by cwen0** [comment]
@AndyXia23 Can you run the following commons to get more information?

```
kubectl describe pod tidb-cluster-pd-0 -n  tidb-admin  
kubectl get pvc -n  tidb-admin 
```

**Comment by AndyXia23** [comment]
### kubectl describe pod tidb-cluster-pd-0 -n  tidb-admin  
Name:               tidb-cluster-pd-0
Namespace:          tidb-admin
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             app.kubernetes.io/component=pd
                    app.kubernetes.io/instance=tidb-cluster
                    app.kubernetes.io/managed-by=tidb-operator
                    app.kubernetes.io/name=tidb-cluster
                    controller-revision-hash=tidb-cluster-pd-d9459457d
                    statefulset.kubernetes.io/pod-name=tidb-cluster-pd-0
Annotations:        pingcap.com/last-applied-configuration:
                      {"volumes":[{"name":"annotations","downwardAPI":{"items":[{"path":"annotations","fieldRef":{"fieldPath":"metadata.annotations"}}]}},{"name...
                    prometheus.io/path: /metrics
                    prometheus.io/port: 2379
                    prometheus.io/scrape: true
Status:             Pending
IP:                 
Controlled By:      StatefulSet/tidb-cluster-pd
Containers:
  pd:
    Image:       pingcap/pd:v3.0.1
    Ports:       2380/TCP, 2379/TCP
    Host Ports:  0/TCP, 0/TCP
    Command:
      /bin/sh
      /usr/local/bin/pd_start_script.sh
    Environment:
      NAMESPACE:          tidb-admin (v1:metadata.namespace)
      PEER_SERVICE_NAME:  tidb-cluster-pd-peer
      SERVICE_NAME:       tidb-cluster-pd
      SET_NAME:           tidb-cluster-pd
      TZ:                 UTC
    Mounts:
      /etc/pd from config (ro)
      /etc/podinfo from annotations (ro)
      /usr/local/bin from startup-script (ro)
      /var/lib/pd from pd (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-g8ktr (ro)
Volumes:
  pd:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pd-tidb-cluster-pd-0
    ReadOnly:   false
  annotations:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.annotations -> annotations
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      tidb-cluster-pd-aa6df71f
    Optional:  false
  startup-script:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      tidb-cluster-pd-aa6df71f
    Optional:  false
  default-token-g8ktr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-g8ktr
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

### kubectl get pvc -n  tidb-admin
NAME                   STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS    AGE
pd-tidb-cluster-pd-0   Pending                                      local-storage   6d22h
pd-tidb-cluster-pd-1   Pending                                      local-storage   6d22h
pd-tidb-cluster-pd-2   Pending                                      local-storage   6d22h

**Comment by cwen0** [comment]
@AndyXia23 Can you run `kubectl get pv` and check if there are available PVS currently?

The other way, if you just want to try Chaos Mesh, I think you can try the other target cluster, like: https://github.com/pingcap/chaos-mesh/tree/master/examples/web-show

**Comment by AndyXia23** [comment]
@cwen0 
I tried the way you just recommended to me but it didn't seem to work. It got stuck in a certain command "Waiting for pod running". Can I execute "deploy.sh" in example web-show successfully in mainland China without VPN?

**Comment by cwen0** [comment]
If you can't access to docker.io, you can try `./deploy.sh --docker-mirror`, `--docker-mirror` will use a mirror registry in china to pull the docker image. when the `web-show` was installed successfully, you can access to http://localhost:8081/ to open the  front-end.

**Comment by cwen0** [comment]
@AndyXia23  You can see a graph showing ping latency on the front-end of web-show. 
You can run `kubectl apply -f network-delay.yaml` to start a network chaos experiment and  you can see the effect of the experiment from the front-end.
eg: 
![image](https://user-images.githubusercontent.com/22956341/76099011-6ee7a800-6005-11ea-95aa-630c6aa750a4.png)

**Comment by AndyXia23** [comment]
@cwen0 
After I deployed the _web-show_ in a physical mechine, can I access to http:// <phsical mechine IP>:8081 to open the front-end using my own laptop?

**Comment by cwen0** [comment]
@AndyXia23 Yes, If you deploy your kind cluster on your own laptop, you can access it on with http://localhost:8081.

**Comment by cwen0** [comment]
> @cwen0
> After I deployed the _web-show_ in a physical machine, can I access to http:// :8081 to open the front-end using my own laptop?

Yes, this is ok, you can use the physical machine's IP address to access the front-end using my own laptop?

**Comment by AndyXia23** [comment]
@cwen0 Due to your help, I accessed it but how to reduce the spacing of the abscissa? After I ran `kubectl apply -f network-delay.yaml`, the effect was not obvious. 
The image in my laptop is like this:
![图片](https://user-images.githubusercontent.com/59043762/76135725-c49f6d00-6064-11ea-8c70-871f2b4e2439.png)

**Comment by cwen0** [comment]
@AndyXia23 Can you run the following command to get logs? 

```
kubectl get pod --namespace=chaos-testing | grep controller | awk '{print $1}' | xargs -I {} kubectl logs {} -n chaos-testing
```

**Comment by cwen0** [comment]
@AndyXia23 `network-delay.yaml` is the file on [`examples/web-show`](https://github.com/pingcap/chaos-mesh/blob/master/examples/web-show/network-delay.yaml) path?

**Comment by AndyXia23** [comment]
@cwen0 Yes, it is the file on `examples/web-show ` path. 
There are some errors in logs:
![图片](https://user-images.githubusercontent.com/59043762/76137609-08e93800-607a-11ea-8143-e3460d451123.png)

**Comment by cwen0** [comment]
@AndyXia23 Can you check the content of `network-delay.yaml`? From your logs, you start a pod-failure experiment not network chaos.  And you can run the following comment to get all networkchaos? 

```
kubectl get networkchaos.pingcap.com --all-namespaces
 kubectl get podchaos.pingcap.com --all-namespaces

**Comment by AndyXia23** [comment]
@cwen0 
![图片](https://user-images.githubusercontent.com/59043762/76140229-fdeed180-6092-11ea-869a-d223c164fd49.png)

**Comment by AndyXia23** [comment]
@cwen0 
$ kubectl get networkchaos.pingcap.com --all-namespaces
NAMESPACE   NAME                    AGE
default     network-delay-example   5h55m
$ kubectl get podchaos.pingcap.com --all-namespaces
NAMESPACE       NAME                  AGE
chaos-testing   pod-failure-example   40h

**Comment by AndyXia23** [comment]
@cwen0 
I guess the error is caused that I deployed chaos-mesh according to `README.md` but failed due to the failure of the mirror download. How can I delete those deployments completely?

**Comment by cwen0** [comment]
@AndyXia23 
You can try the following comments to delete Chaos Mesh: 

```
# helm 2
helm delete chaos-mesh --purge 

# helm 3
helm delete chaos-mesh -n chaos-testing
``` 

And you can refer here https://github.com/pingcap/chaos-mesh/blob/master/doc/run_chaos_mesh.md#delete-a-chaos-experiment to delete the chaos experiment

**Comment by AndyXia23** [comment]
@cwen0 How can I delete these deployments?
```
$ kubectl get po -n tidb-admin
NAME                                      READY   STATUS    RESTARTS   AGE
tidb-cluster-discovery-84d6cf454c-bh88l   1/1     Running   0          7d20h
tidb-cluster-monitor-6c6645d89f-xspfc     3/3     Running   0          7d20h
tidb-cluster-pd-0                         0/1     Pending   0          7d20h
tidb-cluster-pd-1                         0/1     Pending   0          7d20h
tidb-cluster-pd-2                         0/1     Pending   0          7d20h
```

The issue still exists that the image in the front-end is not like that you showed.
The content of `network-delay.yaml `is as follow:
```
apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-example
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "app": "web-show"
  delay:
    latency: "10ms"
    correlation: "100"
    jitter: "0ms"
  duration: "30s"
  scheduler:
    cron: "@every 60s"
```

**Comment by cwen0** [comment]
@AndyXia23  I think this document can help you https://pingcap.com/docs/stable/tidb-in-kubernetes/maintain/destroy-tidb-cluster/#destroy-tidb-clusters-in-kubernetes 

Can you check the status of chaos mesh pods? 

```
kubectl get pod -n chaos-testing
```

**Comment by AndyXia23** [comment]
@cwen0 
```
$ kubectl get pod -n chaos-testing
No resources found.
```

**Comment by cwen0** [comment]
@AndyXia23 

haha, from the message, The Chaos Mesh has been deleted by you successfully.

**Comment by AndyXia23** [comment]
@cwen0 
Thank you for your help.
