### ISSUE TITLE
UCP: combine the multi actions of networkchaos into one action named `netem`

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#346]
## Description

Sometimes, users want to apply network chaos that combines delay and loss at the same time, and delay action, loss action, corrupt action, duplicate action of NetworkChaos has the same implementation logic, so the `action` field for NetworkChaos take no effect and we can combine delay action, loss action, corrupt action, duplicate action into one action named `netem`  

https://github.com/pingcap/chaos-mesh/blob/master/api/v1alpha1/networkchaos_types.go#L31-L42   
https://github.com/pingcap/chaos-mesh/blob/master/controllers/networkchaos/types.go#L63 
https://github.com/pingcap/chaos-mesh/blob/master/controllers/networkchaos/types.go#L78

## Score

50

## Mentor(s)

* @cwen0 

Contact the mentors: #tidb-challenge-program channel in TiDB Community Slack Workspace

## Recommended Skills

* Golang
* `tc` command

## Learning Materials

* [Development guide of chaos-mesh](https://github.com/pingcap/chaos-mesh/wiki/Development-Overview) 
* [Chaos-mesh Contributing Tutorial](https://yisaer.gitbook.io/chaos-mesh-contributing-tutorials/)

**Comment by at15** [comment]
Just want some clarification before I start working on the issue.

Currently although the underlying daemon allows combine delay, loss etc. but it seems the controller is only sending the one specified by the action field. So even if I give both delay and loss in the spec, only one will be triggered. Spec is picked based on value of action field, converted to netem request and send to chaosdaemon.

https://github.com/pingcap/chaos-mesh/blob/5f4bbca9f450460099afe23cfe2368c667b04aab/controllers/networkchaos/netem/types.go#L237-L265

Each spec implements their own `ToNetem`

https://github.com/pingcap/chaos-mesh/blob/50740fc13ad304c3109fc60abb3a01ac205d8c49/api/v1alpha1/networkchaos_types.go#L324-L339

https://github.com/pingcap/chaos-mesh/blob/50740fc13ad304c3109fc60abb3a01ac205d8c49/api/v1alpha1/networkchaos_types.go#L347-L362

On daemon side it simply apply everything sends in the rpc

https://github.com/pingcap/chaos-mesh/blob/8c70bf6f0ec55e0e5fe006a6394217201a8d709b/pkg/chaosdaemon/types.go#L22-L38

In pseudo code the current logic is

```
spec = {
  action: loss
   loss: { 
      loss: 25
      lossCorr: 25
   }
   delay: {
      latency: 90ms
   }
}

createController {
switch action:
  case loss, delay...
      newCommon
  case partition
      newTwoPhase
}
 
common reconcile {
    fieldName = action
    req = NetworkChaos.filedName.ToNetem // only pick the one specified by action
    pbclient.send(req)
}

daemon {
    reqHandler {
      netlink bla bla
   }
}
```

If we want to merge them and allow backward comparability, we could add `netem` as the new action and mark the old ones as deprecated (not sure if k8s support it). And when generating rpc request from chaos yaml, we call `ToNetem` for all the emulation specs and merge them into one (as long as they don't have conflict and the empty values make sense) 

```
createController {
case netem, delay, loss ...
    newCommon
}

common reconcile {
switch action
   case partition
        panic("two phase reconcile expected")
  case netem:
       var netem
       mergeNetem(netem, spec.Loss.ToNetem)
       mergeNetem(netem, spec.Delay.ToNetem)
       // ...
  default: // default is the old reflection based picking spec ...
         fieldName = action
         req = NetworkChaos.filedName.ToNetem // only pick the one specified by action
}

mergeNetem (a, b) c {
  return &Netem {
        Time: max(a.Time. b.Time)
        ....
   }
}

**Comment by YangKeao** [comment]
@at15 Thanks for your contribution. I think this roadmap is good enough.

But in Kubernetes crd, action enum is only a string. So there may be no way to deprecate it. @cwen0 Do you have any suggestions on this?

**Comment by at15** [comment]
We can add logic in [validation webhook](https://github.com/pingcap/chaos-mesh/blob/master/api/v1alpha1/networkchaos_webhook.go) and reject other actions `delay`, `loss` etc. after `netem` is released for a while.

Another way is using [MutatingAdmissionWebhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook) but this might confusion for user.

**Comment by YangKeao** [comment]
@at15 It's definitely acceptable, though rejecting is not a `deprecated` behavior, does it? Can the users bypass the validation? But it seems the best solution now.

In crd configuration yaml files, there is a field called `deprecated`. However, kubebuilder cannot generate it automatically (I didn't find a way to set it through annotation).

**Comment by at15** [comment]
@YangKeao I don't think user can bypass admission webhook.  We just tell user we are going deprecate it and then remove it. Besides I think current spec is still in a flux because peopling are considering adding advanced behavior #295 and different backend #307 

I didn't notice that field, might create a issue in kubebuilder.

**Comment by at15** [comment]
lol it seems I wrote the wrong issue number is the merged PR https://github.com/pingcap/chaos-mesh/pull/353, it should be `346` instead of `345`  Can someone close this PR directly? Or we can leave it open until we add the webhook part.

**Comment by cwen0** [comment]
@at15 I think we can close this pr.
