### ISSUE TITLE
Support incremental build

### ISSUE THREAD

**Issue by yujunz** [pingcap/chaos-mesh#362]
## Feature Request

**Is your feature request related to a problem? Please describe:**
No

**Describe the feature you'd like:**
binary seems always rebuilt regardless code changes. 

```
make image-chaos-mesh
make image-chaos-daemon
```

`pingcap/binary` will be built twice although it is not changed at all between the two steps. This is slowing down the development process.

**Describe alternatives you've considered:**
Options for solution of incremental build
* mount build cache to container
* looks for alternative toolchain other than make

**Comment by YangKeao** [comment]
Sorry. I didn't reproduce this problem. Docker will cache the build result, doesn't it? Can you provide your docker version?

```
docker build -t pingcap/binary  .

Sending build context to Docker daemon  83.99MB
Step 1/18 : FROM golang:alpine3.10 AS build_base
 ---> dd50f8b1f673
Step 2/18 : ARG HTTPS_PROXY
 ---> Using cache
 ---> ed05e4f428f0
Step 3/18 : ARG HTTP_PROXY
 ---> Using cache
 ---> 4d7a51c92635
Step 4/18 : RUN apk add --no-cache gcc g++ make bash git
 ---> Using cache
 ---> b8b43c5ddfe7
Step 5/18 : ENV GO111MODULE=on
 ---> Using cache
 ---> 76f8023e6424
Step 6/18 : RUN mkdir /src
 ---> Using cache
 ---> 1fcf57f78a5e
Step 7/18 : WORKDIR /src
 ---> Using cache
 ---> bf4900ff1bb1
Step 8/18 : COPY go.mod .
 ---> Using cache
 ---> 7561d5e369fc
Step 9/18 : COPY go.sum .
 ---> Using cache
 ---> 722ca97f3341
Step 10/18 : RUN go mod download
 ---> Using cache
 ---> b0f51f67a398
Step 11/18 : RUN go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.5
 ---> Using cache
 ---> bb42256913bd
Step 12/18 : RUN go get golang.org/x/tools/cmd/goimports
 ---> Using cache
 ---> 26ddc7dc965e
Step 13/18 : FROM build_base AS binary_builder
 ---> 26ddc7dc965e
Step 14/18 : ARG HTTPS_PROXY
 ---> Using cache
 ---> 35bb41474e77
Step 15/18 : ARG HTTP_PROXY
 ---> Using cache
 ---> d0611c76dfff
Step 16/18 : COPY . /src
 ---> Using cache
 ---> f4d2df8381db
Step 17/18 : WORKDIR /src
 ---> Using cache
 ---> 43bc719066ee
Step 18/18 : RUN make binary
 ---> Using cache
 ---> ef5d8e754010
Successfully built ef5d8e754010
Successfully tagged pingcap/binary:latest
```

**Comment by yujunz** [comment]
The cache works only when **nothing** changes at all. A minor line change of one source file seems triggering a complete rebuilt.

I think docker is not wise enough to cache `go build` incrementally.

**Comment by AngleNet** [comment]
Docker calculates a checksum for ‘ADD’ and ‘COPY’. It is inevitable for now. I think

**Comment by YangKeao** [comment]
We have cached `go mod download` in a seperate image. If `go.mod` and `go.sum` doesn't change, we don't need to download dependency again.

Is there any way to cache `go build`? Is it necessary (`go build` won't cost much time)?

It seems that `go vet` costs a lot of time in `make` stage. Maybe we should skip it?

**Comment by yujunz** [comment]
> Is there any way to cache `go build`? Is it necessary (`go build` won't cost much time)?
Not sure about where and how `go build` cache intermediate results. If it costs too much time, we may revisit it later.

> It seems that `go vet` costs a lot of time in `make` stage. Maybe we should skip it?

 +1 for removing `go vet` from manual build. Maybe just include it in CI for quality assurance.

**Comment by yujunz** [comment]
It may worth try some tips and tricks from https://medium.com/windmill-engineering/tips-tricks-for-making-your-golang-container-builds-10x-faster-4cc618a43827 for containerized build of go apps.
