### ISSUE TITLE
UCP: Using more Validator and Defaulter, more friendly for user

### ISSUE THREAD

**Issue by Gallardot** [pingcap/chaos-mesh#365]
## Description 

Through implement the Defaulter and the Validator interface, We have  implemented admission webhooks for chaos object. But currently we only have some simple rules.I think more rules can make chaos-mesh more friendly for user.
for example A:
https://github.com/pingcap/chaos-mesh/blob/41b31e5e3375654e24d83932dd624d15a191fa31/api/v1alpha1/common_types.go#L65-L75

**Cron should be match the spec rules**

for example B:
https://github.com/pingcap/chaos-mesh/blob/41b31e5e3375654e24d83932dd624d15a191fa31/api/v1alpha1/networkchaos_types.go#L248-L274

**DelaySpec.Latency and DelaySpec.Jitter should be time format.**

If user typo, execute `kubectl create -f chaos.yaml` is OK. But it doesn't actually work. The user can only check the log of chaos-mesh. It's a waste of time.

So I think make more Validation rules by the `webhook.Validator` and(or)  [crd-validation](https://book.kubebuilder.io/reference/markers/crd-validation.html) is more friendly for user.If user typo, user knows immediately what the problem is.

At least 5 cheker for the chaos objects

1. `Specific format checker`
2. `Value range checker`
3. `Null checker`
4. `Regular checker`
5.  `Combination checker`
6.  etc......

I think this proposal also match the [TiDB Usability Challenge Program](https://github.com/pingcap/community/blob/master/challenge-programs/challenge-program-season-2.md).  😄

## Score 

* 936

## Mentor(s)

* @cwen0

Contact the mentors: #tidb-challenge-program channel in TiDB Community Slack Workspace

## Recommended Skills

* Golang
* Kubernetes

## Learning Materials

* [Development guide of chaos-mesh](https://github.com/pingcap/chaos-mesh/wiki/Development-Overview) 
* [Chaos-mesh Contributing Tutorial](https://yisaer.gitbook.io/chaos-mesh-contributing-tutorials/)
*  [crd-validation](https://book.kubebuilder.io/reference/markers/crd-validation.html)

**Comment by cwen0** [comment]
> I think this proposal also match the TiDB Usability Challenge Program. 😄 

Thanks for your proposal, this is a good suggestion. We can split this proposal to multi easy tasks.

**Comment by you06** [comment]
@Gallardot try again please
