### ISSUE TITLE
development tutorial: need export DOCKER_REGISTRY to localhost:5000

### ISSUE THREAD

**Issue by hoang-tranviet** [pingcap/chaos-mesh#381]
## Bug Report

**What version of Kubernetes are you using?**
v1.15.5

**What did you do?**
I follow the development tutorial in https://github.com/pingcap/chaos-mesh/wiki/Develop-a-New-Chaos.

Below does not work
```
make
make docker-push

```
**What did you expect to see?**
It should build images and push to local registry

**What did you see instead?**
I cannot push to local registry.

@vincent suggests that we need to set the DOCKER_REGISTRY to localhost:5000

I think it is easier for new comers if it is mentioned in the tutorial.

**Comment by cwen0** [comment]
@hoang-tranviet Do you mean that we set `localhost:5000` as the default value of `DOCKER_REGISTRY`?

**Comment by hoang-tranviet** [comment]
Hi @cwen0,
When first read the tutorial, I understood wrongly that we don't need to set DOCKER_REGISTRY since it is preset as local registry (localhost:5000) in `hack/kind-cluster-build.sh`.

Now I understand (could be also wrong) that `hack/kind-cluster-build.sh` is set to pull images from localhost:5000, and I need to set by myself `export DOCKER_REGISTRY=localhost:5000` to let `make`and `make docker-push` work. 
I think the tutorial could add `export DOCKER_REGISTRY=localhost:5000` before these `make` commands, and clarify what each command does to avoid confusion.

**Comment by cwen0** [comment]
@Yisaer PTAL

**Comment by Yisaer** [comment]
I guess the wiki tutorial might be out-of-date. I didn't find `hack/kind-cluster-build.sh` preset the `DOCKER_REGISTRY` nor in `Makefile`

The `make` command would generate the code, build the binary and the image.  so if you want to build the image and push to your own docker registry, I suggest you to follow:
```sh
DOCKER_REGISTRY=<you-own-host> make
DOCKER_REGISTRY=<you-own-host> make docker-push
``

**Comment by hoang-tranviet** [comment]
I close since the Docker registry seems to be not used any more, at least not on Kind.
