### ISSUE TITLE
After I run 'helm install', it appears 'Error: validation failed'

### ISSUE THREAD

**Issue by SilvaXiang** [pingcap/chaos-mesh#382]
## Bug Report

**What version of Kubernetes are you using?**
My Kubernetes version is v1.14.8
My helm version is v2.16.4
![image](https://user-images.githubusercontent.com/22973642/77638709-8d045080-6f92-11ea-834c-902692cac0b2.png)

**What did you do?**
I try to deploy [chaos-mesh](https://github.com/pingcap/chaos-mesh/wiki/Deploy-Chaos-Mesh) in my k8s cluster, but when I run this command `helm install helm/chaos-mesh --name=chaos-mesh --namespace=chaos-testing` in Step 3, something is wrong. It as follows:
`Error: validation failed: [serviceaccounts "chaos-controller-manager" not found, clusterroles.rbac.authorization.k8s.io "chaos-mesh:chaos-controller-manager" not found, clusterrolebindings.rbac.authorization.k8s.io "chaos-mesh:chaos-controller-manager" not found, services "chaos-mesh-controller-manager" not found, daemonsets.apps "chaos-daemon" not found, deployments.apps "chaos-controller-manager" not found, mutatingwebhookconfigurations.admissionregistration.k8s.io "chaos-mesh-sidecar-injector" not found, validatingwebhookconfigurations.admissionregistration.k8s.io "chaos-mesh-validation" not found]`

**Comment by Yisaer** [comment]
This is the bug caused by latest helm v2 release 2.16.4. You need downgrade your helm version under v2.16.4. @SilvaXiang 

For more details, https://github.com/helm/helm/issues/7797

**Comment by Yisaer** [comment]
@SilvaXiang I think downgrading helm version might solve this problem, If you meet any installing error after downgrading. You can reopen this issue.

**Comment by SilvaXiang** [comment]
> This is the bug caused by latest helm v2 release 2.16.4. You need downgrade your helm version under v2.16.4. @SilvaXiang
> 
> For more details, [helm/helm#7797](https://github.com/helm/helm/issues/7797)

Ok,thanks. I solved it by downgrading the version of helm yesterday. But I forgot to reply. Sorry.
