### ISSUE TITLE
Forbidden: pod updates may not add or remove containers

### ISSUE THREAD

**Issue by ycwdaaaa** [pingcap/chaos-mesh#386]
I meet this error When try to inject a net delay container to  pod using the json-patch .    How did you guys inject the sidecar container?  I found that only inject container for deployment worked.  inject pod will meet the error

**Comment by zhouqiang-cl** [comment]
The net delay did not need to inject sidecar. Only IO Chaos needs to inject sidecar. 


> I found that only inject container for deployment worked. inject pod will meet the error

I am a little did not understand this. could you make it more clear

**Comment by ycwdaaaa** [comment]
but if do not inject a sidecar container, how do we trigger a network drop or delay event?  there is no tc or iptables in some containers in our project

**Comment by zhouqiang-cl** [comment]
@YangKeao @cwen0 PTAL


> but if do not inject a sidecar container, how do we trigger a network drop or delay event? there is no tc or iptables in some containers in our project

Yes. we have a daemonset that have tc/iptables

**Comment by ycwdaaaa** [comment]
Thank you very much for answering my questions, so can I ask one more? if use ds to deploy network traffic container per node, how can we make sure the network drop only works on one pod?

**Comment by AngleNet** [comment]
We will find the network namespace of the targeted pods or containers. The network chaos actually happen over these namespaces.

**Comment by ycwdaaaa** [comment]
> We will find the network namespace of the targeted pods or containers. The network chaos actually happen over these namespaces.

Thank you very much for your answer.  so in  IO Chaos  we need the sidecar right?  When I try to  add container  by json-patch, I meet the error : Forbidden: pod updates may not add or remove containers.  Do you have any idea?

**Comment by YangKeao** [comment]
> 
> 
> @YangKeao @cwen0 PTAL
> 
> > but if do not inject a sidecar container, how do we trigger a network drop or delay event? there is no tc or iptables in some containers in our project
> 
> Yes. we have a daemonset that have tc/iptables

Actually it doesn't need tc. `chaos-daemon` use [`netlink` ](http://man7.org/linux/man-pages/man7/netlink.7.html) directly.

**Comment by YangKeao** [comment]
> 
> 
> > We will find the network namespace of the targeted pods or containers. The network chaos actually happen over these namespaces.
> 
> Thank you very much for your answer. so in IO Chaos we need the sidecar right? When I try to add container by json-patch, I meet the error : Forbidden: pod updates may not add or remove containers. Do you have any idea?

As it suggested, you can not add container for a running pod. You could modify the corresponding `deployment` or delete this and create a new pod (with injected container). You can also modify the pod before it launched with the help of webhook.

If you really want to inject a container for a running pod, you can try [Ephemeral Containers](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/).

**Comment by ycwdaaaa** [comment]
if use webhook like chaos-mesh to inject sidecar,  I need deploy the webook first then deploy the pod right?

**Comment by YangKeao** [comment]
@ycwdaaaa Yes 😄

**Comment by zhouqiang-cl** [comment]
@ycwdaaaa Did every thing is ok now?

**Comment by ycwdaaaa** [comment]
> @ycwdaaaa Did every thing is ok now?

I have one more question~~  due to our k8s version is 1.8. so I cannot use chaos-mesh....  I see the doc that chaos-mesh need the version at least 1.13.  I have to inject by myself~   So Can you teach me how to inject network delay by DS ?  how to find the pod's network namespace then inject network delay? Or can you lead me to your source code?

**Comment by YangKeao** [comment]
@ycwdaaaa You can follow these steps to inject network delay manually:

1. Found container id of pod's container with `kubectl describe` (they may start with `docker://` or `containerd://`)

2. Use container id to find PID on the related node (with the help of `docker` or `ctr`). Then `/proc/$PID/ns/net` is related network namespace.

3. Then you can use `nsenter` to change to this network namespace and use `tc-netem` to inject delay. 

A friendly reminder:

```
The Kubernetes project maintains release branches for the most recent three minor releases.
```

So a too old version of Kubernetes is not recommended to use.

**Comment by ycwdaaaa** [comment]
@YangKeao Thank you so much~~ I will follow your steps

**Comment by ycwdaaaa** [comment]
@YangKeao btw, does these steps can be automatic?

**Comment by YangKeao** [comment]
@ycwdaaaa Yes! It definitely can be automatic and that's why we developed chaos-mesh. But chaos-mesh doesn't support too old version of Kubernetes (as you have found).

**Comment by ycwdaaaa** [comment]
@YangKeao
I follow your steps and successfully  inject network delay and loss， thanks so much.   So can I do something like this to inject cpu load or process killer?

**Comment by zhouqiang-cl** [comment]
> @YangKeao
> I follow your steps and successfully inject network delay and loss， thanks so much. So can I do something like this to inject cpu load or process killer?

CPU load is still work in progress in https://github.com/pingcap/chaos-mesh/pull/332
You can inject pod failure(pod-kill/pod-failure/container-kill)

**Comment by ycwdaaaa** [comment]
@YangKeao 
so how to do these without chaos-mesh~~ you know it, out k8s version is 1.8.. I cannot use chaos-mesh.   
For kill pod, I can invoke client-go finish it. but for cpu load and process kill?

**Comment by zhouqiang-cl** [comment]
hi, @ycwdaaaa  you can use `stress-ng` like https://github.com/pingcap/chaos-mesh/pull/332

**Comment by ycwdaaaa** [comment]
hi, @YangKeao  I mean how to inject~~  For network,  thanks very much that I can find out the container net namespace to inject by following your step.  So for these accident type, can I use like this way to find like process namespace to kill process?  or  find the cgroups of container to inject a cpu load in the same cgroups?

**Comment by zhouqiang-cl** [comment]
@AngleNet PTAL
