### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by tsingloon** [pingcap/chaos-mesh#390]
## Question
use https://github.com/pingcap/chaos-mesh/blob/master/examples/pod-kill-example.yaml to test pod

Error from server (InternalError): error when creating "test_pod.yaml": Internal error occurred: failed calling webhook "mpodchaos.kb.io": Post https://chaos-mesh-controller-manager.chaos-testing.svc:443/mutate-pingcap-com-v1alpha1-podchaos?timeout=30s: x509: certificate signed by unknown authority

**Comment by zhouqiang-cl** [comment]
@tsingloon I see you have close this issue, did you have already do chaos experiments success?

**Comment by huangwei2013** [comment]
Got the same problem and find no way
