### ISSUE TITLE
Seems the public key used in images/chaos-kernel/Dockerfile is unavailable

### ISSUE THREAD

**Issue by YangKian** [pingcap/chaos-mesh#392]
## Bug Report

**What version of Kubernetes are you using?**
Not relevant

**What did you do?**
Following the guide "setup the development environment" until `make` command

**What did you expect to see?**
The make command should pass successfully

**What did you see instead?**
When building docker image with dockfile in `images/chaos-kernel/Dockerfile`, I get an error:

```
W: GPG error: https://apt.kitware.com/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 291F9FF6FD385783
E: The repository 'https://apt.kitware.com/ubuntu bionic InRelease' is not signed.
```

Check the dockerfile, I found this command:

`RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8611B7A28669BB93`

seems like the public key is unavailable.

Try to fix the problem in my local machine by replacing the command in the dockerfile to 

`RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 291F9FF6FD385783`

Since I don't have another machine to test if it is a common problem, would it be nice to fix it?

**Comment by hoang-tranviet** [comment]
I got the same error, but since I am on Fedora, I add this key using `rpm --import` instead.

**Comment by zhouqiang-cl** [comment]
@cwen0 @YangKeao PTAL

**Comment by YangKeao** [comment]
I think we should get asc key dynamically with `wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add -`, which is also suggested by [kitware website](https://apt.kitware.com/)

**Comment by YangKian** [comment]
> I think we should get asc key dynamically with `wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add -`, which is also suggested by [kitware website](https://apt.kitware.com/)

Yep, I think it's the best way！I also tried to find a way to update dynamically yesterday, but I didn't find it_(:з」∠)_  thanks for the link
