### ISSUE TITLE
Question: Will chaos recover if controller manager crashed after applying chaos

### ISSUE THREAD

**Issue by at15** [pingcap/chaos-mesh#393]
## Question

While working on #373 I checked the recover is triggered using `ctrl.Result{RequeueAfter: duration}`.
Which is implemented in controller runtime and does not persistent into API server.
The reconcile logic of controller is triggered when there is something in the queue (update, requeue etc.). If the manager pod crashed after applying a chaos, nothing will trigger reconcile logic. Chaos daemon does not update the status field, it is updated by controller.

It's just an assumption I didn't validate that ...  Regardless of the correctness of the assumption, I think we need a way to nuke all the chaos in the cluster to bring things back to normal even if the controller is not working.

https://github.com/pingcap/chaos-mesh/blob/093337c1f46cef80af4a8788101444efaff99cb8/controllers/twophase/types.go#L181

**Comment by zhouqiang-cl** [comment]
@cwen0 @YangKeao PTAL

**Comment by YangKeao** [comment]
As I have tested several months ago, when the controller manager starts, it will reconcile all existing Chaos Objects, so nothing can go wrong.

But I didn't look into `controller-runtime`'s codes to make sure.

**Comment by at15** [comment]
Checked controller-runtime behavior, it load all the CRDs when starts and calls Reconcile. So the recover logic should still get triggered after controller restarts as long as nextRecover is updated after chaos is applied. This also applies to starting chaos as well.

https://github.com/pingcap/chaos-mesh/blob/093337c1f46cef80af4a8788101444efaff99cb8/controllers/twophase/types.go#L108
