### ISSUE TITLE
Is there a way to use kubectl apply yaml file to deploy chaos-mesh instead of helm?

### ISSUE THREAD

**Issue by wwjgit** [pingcap/chaos-mesh#409]
We'd like to use chaos-mesh on a cluster which has limited access to network. How to deploy chaos-mesh onto this kind of environment? We can pull and tag the related images in advance for the cluster.

**Comment by Yisaer** [comment]
Hi @wwjgit ,
You could use `helm template` to generate the target yaml file in the external environment. Then you can bring these yaml files to your env and install the chaos-mesh offline.
eg:
> helm template pingcap/chaos-mesh --version=<version> --name <name> --values values.yaml > target.yaml

**Comment by Yisaer** [comment]
I think this method have answered your question, feel ok to reopen the issue if you have any further questions.
