### ISSUE TITLE
IOChaos supports smaller probability of failure injection

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#413]
## Feature Request

**Is your feature request related to a problem? Please describe:**

At present, we support to define the percentage of injection errors and provides a number from 0-100 when to use IOChaos, but sometimes we want the smaller probability, such as 0.01% 
 
**Describe the feature you'd like:**
 

We can use a float64 type to define the percentage of failure injection.

**Comment by RajatVaryani** [comment]
@cwen0 Can I pick this up?

**Comment by cwen0** [comment]
@RajatVaryani Of course, thanks for your participation.
