### ISSUE TITLE
The pods are expected to be running when checking Chaos Mesh pods installed?

### ISSUE THREAD

**Issue by wwjgit** [pingcap/chaos-mesh#416]
What pods should be up and running after installing chaos-mesh successfully? A pod list should be useful.

**Comment by fewdan** [comment]
@wwjgit 
After installation, you will see "chaos-controller-manager" and "chaos-daemon". The number of "chaos-daemon" is related to the k8s cluster.

**Comment by wwjgit** [comment]
@fewdan No chaos-daemon running on my system. Below warning message reported.    
spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used 
spec.volumes[0].hostPath.pathPrefix: Invalid value: "/var/run/docker.sock": is not allowed to be used

**Comment by fewdan** [comment]
@wwjgit 
Would you please provide more information?  For example, what is your environment? Did you install it using "kind"? 
Also, you can check whether your docker is normal. Thank you.

**Comment by wwjgit** [comment]
@fewdan It is k8s cluster with 20 nodes. Not a kind or minikube cluster. The docker is running well.

**Comment by zhouqiang-cl** [comment]
> @fewdan No chaos-daemon running on my system. Below warning message reported.
> spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used
> spec.volumes[0].hostPath.pathPrefix: Invalid value: "/var/run/docker.sock": is not allowed to be used

Hi, @wwjgit could you provide the yaml file and at which step it report this issue, please also provide k8s version, thank you

**Comment by wwjgit** [comment]
Hi, @zhouqiang-cl, please find the version and yaml file below. 

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.10", GitCommit:"e3c134023df5dea457638b614ee17ef234dc34a6", GitTreeState:"clean", BuildDate:"2019-07-08T03:50:59Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.6-45+c49c6cc7ec3af7", GitCommit:"c49c6cc7ec3af777e580543db675b2d54533afaf", GitTreeState:"clean", BuildDate:"2019-03-20T07:45:02Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: chaos-daemon
  labels:
    app.kubernetes.io/name: chaos-mesh
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/component: chaos-daemon
    helm.sh/chart: chaos-mesh-dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chaos-mesh
      app.kubernetes.io/instance: chaos-mesh
      app.kubernetes.io/component: chaos-daemon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chaos-mesh
        app.kubernetes.io/instance: chaos-mesh
        app.kubernetes.io/component: chaos-daemon
    spec:
      hostIPC: true
      hostPID: true
      containers:
        - name: chaos-daemon
          image: repo.jd.local/k8s/chaos-daemon:latest
          imagePullPolicy: IfNotPresent
          command:
            - /usr/local/bin/chaos-daemon
            - --runtime
            - docker
            - --http-port
            - !!str 31766
            - --grpc-port
            - !!str 11767
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_PTRACE
          volumeMounts:
            - name: socket-path
              mountPath: /var/run/docker.sock
          ports:
            - name: grpc
              containerPort: 31767
              hostPort: 10767
            - name: http
              containerPort: 31766
      volumes:
        - name: socket-path
          hostPath:
            path: /var/run/docker.sock

**Comment by wwjgit** [comment]
And the daemon yaml file is created according to https://github.com/pingcap/chaos-mesh/issues/409

**Comment by zhouqiang-cl** [comment]
@wwjgit today @fewdan will try to reproduce it in our own env

**Comment by wwjgit** [comment]
@zhouqiang-cl  @fewdan I've added the sa to a privileged clusterrolebinding.  The chaos-daemon is up and running.

**Comment by zhouqiang-cl** [comment]
Got. @wwjgit ❤️
