### ISSUE TITLE
service "webhook-service" not found

### ISSUE THREAD

**Issue by huangwei2013** [pingcap/chaos-mesh#418]
## Question
ran on Minikube failure：
> [root@dev-1 examples]# kubectl apply -f pod-failure-example.yaml
Error from server (InternalError): error when creating "pod-failure-example.yaml": Internal error occurred: failed calling webhook "mpodchaos.kb.io": Post https://webhook-service.system.svc:443/mutate-pingcap-com-v1alpha1-podchaos?timeout=30s: service "webhook-service" not found

as refer to k8s service, got relative results : 

> [root@dev-1 ~]# kubectl get svc --all-namespaces
NAMESPACE              NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                          AGE
cert-manager           cert-manager                       ClusterIP   10.107.140.141   <none>        9402/TCP                         16h
cert-manager           cert-manager-webhook               ClusterIP   10.105.137.27    <none>        443/TCP                          16h
chaos-testing          chaos-mesh-controller-manager      ClusterIP   10.106.154.207   <none>        10080/TCP,443/TCP                3d23h
...

**Comment by cwen0** [comment]
@huangwei2013 Can you provide more information about your environment? For example, Kubernetes Version, Helm version and the steps to install Chaos Mesh.  In addition,  Can you check the `ValidatingWebhookConfiguration` by the following command? 

```
kubectl get ValidatingWebhookConfiguration chaos-mesh-validation -o yaml
``` 

Judging from the information provided now, `ValidatingWebhookConfiguration` was not deployed. Can you make sure that `ValidatingAdmissionWebhooks` and `MutatingAdmissionWebhooks` are enabled? You can follow this [doc](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#how-do-i-turn-on-an-admission-controller) to check it.

**Comment by huangwei2013** [comment]
[root@dev-1 ~]# kubectl get ValidatingWebhookConfiguration chaos-mesh-validation -o yaml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: "2020-04-10T03:33:59Z"
  generation: 1
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: chaos-mesh
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: chaos-mesh
    helm.sh/chart: chaos-mesh-dev
  name: chaos-mesh-validation
  resourceVersion: "7424542"
  selfLink: /apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations/chaos-mesh-validation
  uid: dbb1f3c4-26a0-4b23-8de2-186d39520ebd
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: chaos-mesh-controller-manager
      namespace: chaos-testing
      path: /validate-pingcap-com-v1alpha1-podchaos
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: vpodchaos.kb.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - pingcap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podchaos
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: chaos-mesh-controller-manager
      namespace: chaos-testing
      path: /validate-pingcap-com-v1alpha1-iochaos
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: viochaos.kb.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - pingcap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - iochaos
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: chaos-mesh-controller-manager
      namespace: chaos-testing
      path: /validate-pingcap-com-v1alpha1-timechaos
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: vtimechaos.kb.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - pingcap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - timechaos
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: chaos-mesh-controller-manager
      namespace: chaos-testing
      path: /validate-pingcap-com-v1alpha1-networkchaos
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: vnetworkchaos.kb.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - pingcap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - networkchaos
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: chaos-mesh-controller-manager
      namespace: chaos-testing
      path: /validate-pingcap-com-v1alpha1-kernelchaos
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  name: vkernelchaos.kb.io
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - pingcap.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kernelchaos
    scope: '*'
  sideEffects: Unknown
  timeoutSeconds: 30

**Comment by Gallardot** [comment]
@huangwei2013 

the service named`webhook-service` is only mentioned in [manifests.yaml](https://github.com/pingcap/chaos-mesh/blob/50740fc13ad304c3109fc60abb3a01ac205d8c49/config/webhook/manifests.yaml).

Can you provide more information about what's the steps to install Chaos Mesh?

**Comment by huangwei2013** [comment]
@cwen0 @Gallardot  
what about make a IM by wechat， I can share the server and work out togather and faster.
here is no so efficiency 

（v：chrichuang）pls remark of this issue

**Comment by cwen0** [comment]
We need to delete the webhook-service config create by [manifest.yaml](https://github.com/pingcap/chaos-mesh/blob/50740fc13ad304c3109fc60abb3a01ac205d8c49/config/webhook/manifests.yaml), because we don't need it and these configs will overwrite the normal webhook configs. 

![image](https://user-images.githubusercontent.com/22956341/79327933-dc152400-7f47-11ea-9a7d-3c9e7af197f1.png)
![image](https://user-images.githubusercontent.com/22956341/79327963-e800e600-7f47-11ea-8712-661bfef2fae1.png) 

we can use the following commands to delete them: 

```
kubectl delete MutatingWebhookConfiguration mutating-webhook-configuration
kubectl delete ValidatingWebhookConfiguration validating-webhook-configuration
```

**Comment by cwen0** [comment]
@huangwei2013 Can we close this issue?
