### ISSUE TITLE
helm-less install

### ISSUE THREAD

**Issue by rbtcollins** [pingcap/chaos-mesh#431]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I'm always frustrated when installation is not documented clearly using k8s primitives.

**Describe the feature you'd like:**
Please document the installation and runtime requirements for chaos-mesh, so that environments without helm, and where helm has been decided against, can utilise chaos-mesh (or alternatively, explain what runtime services chaos-mesh requires from helm, so we can consider how to deliver those in high-trust environments.

**Describe alternatives you've considered:**
I did consider ranting on Twitter, but it's probably counter-productive ;).

**Teachability, Documentation, Adoption, Migration Strategy:**
Clear minimal installation instructions will permit other packaging system for k8s to quickly package chaos-mesh up as well.

**Comment by cwen0** [comment]
@rbtcollins Make senses!

**Comment by cwen0** [comment]
@rbtcollins We have support helm-less install at #466 , So we can close this issue.

**Comment by rbtcollins** [comment]
Thank you

**Comment by rbtcollins** [comment]
Rather than using --dry-run, I suggest using 'helm template' which will work consulting what is deployed in a k8s cluster

**Comment by cwen0** [comment]
@rbtcollins Thanks for your suggestion.

**Comment by cwen0** [comment]
@rbtcollins #506
