### ISSUE TITLE
Actual releases?

### ISSUE THREAD

**Issue by rbtcollins** [pingcap/chaos-mesh#432]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Running 'latest' images makes rollbacks very hard.

**Describe the feature you'd like:**
It would be nice if you could tag a monotonic series of images - even if every build is properly gated, unintended consequences can still cause rollbacks to be desirable and the lack of discrete tags makes that impossible today.

**Describe alternatives you've considered:**
None

**Teachability, Documentation, Adoption, Migration Strategy:**

![image](https://user-images.githubusercontent.com/499678/79529232-389b4f00-80c0-11ea-80c0-759892962378.png)

**Comment by cwen0** [comment]
@rbtcollins Thanks for your suggestions, we will release version 1.0 this quarter and will continue to maintain a certain release frequency.

**Comment by cwen0** [comment]
@rbtcollins We have release a v0.8.0 version and will continue to maintain a certain release frequency.
