### ISSUE TITLE
go mod download hang when run make command to setup development envirment

### ISSUE THREAD

**Issue by ycwdaaaa** [pingcap/chaos-mesh#434]
I have wait for very long time after run make command. 
![image](https://user-images.githubusercontent.com/18463029/79732066-bdd36d80-8325-11ea-85eb-b55b5cd46abf.png)

I know its build the image, but why it takes so mush time?   I'm in china, is there some package cannot download due to "you know why"?

**Comment by ycwdaaaa** [comment]
timeout:

go: github.com/containerd/cgroups@v0.0.0-20200116170754-a8908713319d: Get https://proxy.golang.org/github.com/containerd/cgroups/@v/v0.0.0-20200116170754-a8908713319d.mod: dial tcp 216.58.200.241:443: i/o timeout
The command '/bin/sh -c go mod download' returned a non-zero code: 1
make: *** [image-binary] 错误 1

**Comment by ycwdaaaa** [comment]
BTW, I have set proxy by export GOPROXY=https://goproxy.io

**Comment by zhouqiang-cl** [comment]
@cwen0 @fewdan PTAL

**Comment by cwen0** [comment]
@ycwdaaaa `make build` command will build binaries in Docker, this is the dockerfile:  https://github.com/pingcap/chaos-mesh/blob/master/Dockerfile, So If you just set `GOPROXY=https://goproxy.io` on your local environment, the `GOPROXY` won't take effect in docker. If you just want to build binary in your local environment, you can run `make binary`. If you want to build in docker and build an image, I think you can set `HTTPS_PROXY` and `HTTP_PROXY` or try to set `GOPROXY=https://goproxy.io` in this [dockerfile](https://github.com/pingcap/chaos-mesh/blob/master/Dockerfile).

**Comment by ycwdaaaa** [comment]
@cwen0  Thanks a lot,   I will follow your step.  BTW  this the thing I want to do :  I'm going to add  a container cpu load chaos  in chaos-mesh, so I follow the doc to  use the make command to check if the development environment is ok.  But I have already installed a k8s cluster by kubeadm.  So  do I have to run make command? Or can I use some other way to develop and deploy the new chaos-mesh to my cluster?

**Comment by ycwdaaaa** [comment]
Do I have more fast way to test?

**Comment by cwen0** [comment]
What command did you run? Chaos Mash doesn't care how the k8s cluster creates, so you can run the chaos-mesh on your environment. In addition, this PR #332 also tries to support container CPU load chaos. So I think you can try the other issue. 😁

> Do I have more fast way to test? 

You can try to add an e2e test for the new chaos.

**Comment by ycwdaaaa** [comment]
@cwen0  just make command. why it cost so much time~~~  BTW,  when the CPU Load
 chaos will be ready for us~~

**Comment by cwen0** [comment]
@ycwdaaaa The make command will build binaries in docker and will download a lot of dependent packages when to build, In addition, the make command will pull many base images for building binary image. So If your network is weak, it will cast much time.  

>  when the CPU Load chaos will be ready for us~~  

@AngleNet

**Comment by at15** [comment]
I think we can publish a builder image w/ `gcc g++ make bash git` to make first time build faster for people with slow network. There are mirrors for dockerhub and this can speed up CI builds as well.

btw: Does pingcap have a common build  image for go applications? If so, we can use that directly.

**Comment by at15** [comment]
And we can add a `make doctor` command to check network and suggests people to set proxy properly if they didn't. Like `brew doctor`, `flutter doctor`

```
// not from real code ...
make doctor
go get timeout, Try add export GOPROXY=https://goproxy.io to your ~/.bashrc and open a new terminal
kubebuilder not found/version to low

// 一顿操作之后
make doctor
一片绿.jpg
```

**Comment by Yisaer** [comment]
> e can publish a builder image w/ `gcc g++ make bash git` to make first time build faster for people with slow network. There are mirrors for dockerhub and this can speed up CI builds as well.

This is a good idea. I think there already existed the image that meet this requirement.
