### ISSUE TITLE
pod failure duration not work

### ISSUE THREAD

**Issue by wwjgit** [pingcap/chaos-mesh#446]
## Bug Report

**What version of Kubernetes are you using?**

v1.12.10

**What did you do?**

kubectl apply -f pod-failure.yaml

pod-failure.yaml as below
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
  namespace: chaos-testing
spec:
  action: pod-failure # the specific chaos action to inject; supported actions: pod-kill/pod-failure
  mode: one # the mode to run chaos action; supported modes are one/all/fixed/fixed-percent/random-max-percent
  duration: "30s" # duration for the injected chaos experiment
  selector: # pods where to inject chaos actions
    namespaces:
      - default  # the namespace of the system under test (SUT) you've deployed
    labelSelectors:
      "tier": "frontend" # the label of the pod for chaos injection
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 1m"

**What did you expect to see?**
The target pod fails every 1m with duration 30s.

**What did you see instead?**
The target pod fails every 1m with duration 1s or 2s.

**Comment by cwen0** [comment]
@wwjgit Can you provide more information about the target pod? Chaos Mesh will modify the image of the target pod and make the pod unavailable. If you delete this pod, the pod-failure will recover.

**Comment by wwjgit** [comment]
@cwen0 

apiVersion: v1
kind: Pod
metadata:
  annotations:
    chaos-mesh-pod-failure-pod-failure-wordpress-image: repo.jd.local/k8s/wordpress:latest
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      wordpress; cpu, memory limit for container wordpress'
    kubernetes.io/psp: restricted-psp
  creationTimestamp: 2020-04-24T02:28:41Z
  generateName: wordpress-68d4989969-
  labels:
    app: wordpress
    pod-template-hash: "2480545525"
    tier: frontend
  name: wordpress-68d4989969-8qmrz
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: wordpress-68d4989969
    uid: 1e4d7f36-837a-11ea-bf43-3cfdfe5f325c
  resourceVersion: "662383884"
  selfLink: /api/v1/namespaces/default/pods/wordpress-68d4989969-8qmrz
  uid: 4fb934cb-85d3-11ea-bf43-3cfdfe5f325c
spec:
  containers:
  - env:
    - name: WORDPRESS_DB_HOST
      value: wordpress-mysql
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: mysql-pass
    image: gcr.io/google-containers/pause:latest
    imagePullPolicy: Always
    name: wordpress
    ports:
    - containerPort: 80
      name: wordpress
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/www/html
      name: wordpress-persistent-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-52zwl
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: kc-bcc-pod24-10-196-108-42.hadoop.jd.local
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: wordpress-persistent-storage
    persistentVolumeClaim:
      claimName: mywordpress-pv-claim
  - name: default-token-52zwl
    secret:
      defaultMode: 420
      secretName: default-token-52zwl
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2020-04-24T02:28:41Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2020-04-24T02:28:42Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: 2020-04-24T02:28:41Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://38e36ed308e94d414b8981384000a21b19dc760067b0590d009bedfaa41d6c64
    image: repo.test.local/k8s/wordpress:latest
    imageID: docker-pullable://repo.test.local/k8s/wordpress@sha256:80eb70636cb754584224aa75d4cba92f76d936e914d338d76ddcdebbfb531f76
    lastState: {}
    name: wordpress
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2020-04-24T02:28:42Z
  hostIP: 10.196.108.42
  phase: Running
  podIP: 10.163.120.54
  qosClass: Guaranteed
  startTime: 2020-04-24T02:28:41Z

**Comment by wwjgit** [comment]
@cwen0 Hi, cwen0, do we have any updates? Or need more information about the issue?

**Comment by cwen0** [comment]
@wwjgit Sorry for the late response. I think it is a bug, some case will make the target pod recreated and make the fake image invalid. I am trying to figure out these cases and fix this.

**Comment by cwen0** [comment]
@wwjgit Hi, I have tested this case, I think the pod-failure have been injected successfully, Although, the status of the pod was running, this pod can't provide service already. You can check the status of your service or check the log of the pod to confirm this. Sometimes, the status of pod changed to `running` because of `gcr.io/google-containers/pause:latest`

**Comment by wwjgit** [comment]
@cwen0 I see. And thanks a lot for the response.

**Comment by yeya24** [comment]
Hi @wwjgit , any updates on this? Is this problem still reproducible to you?
