### ISSUE TITLE
Use annotation of Chaos Object to pause experiment

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#447]
## Feature Request

**Is your feature request related to a problem? Please describe:**

At present, If we want to pause an experiment, we need patch this object, such as: 

```
kubectl patch podchaos pod-kill-example --namespace chaos-testing --type merge --patch 'spec:
 paused: false'
``` 
I think this operation is complicated and incomprehensible. 

**Describe the feature you'd like:**

I recommend that we can use annotation of the object to pause experiment, in the way, we can pause the experiment using the following command: 

```
kubectl annotate podchaos pod-kill-example -n chaos-testing pause='true'
```

**Comment by yeya24** [comment]
So if we have the annotation way, do we still keep the patch way to pause experiments?
If we could have a kubectl plugin, then it would be much more convenient.

**Comment by cwen0** [comment]
@yeya24 I think we can remove the patch way to pause experiment, In addition, this feature may be used in the process, so I think `kubectl plugin` is not available.

**Comment by yeya24** [comment]
Thanks, make sense 💪
