### ISSUE TITLE
When does `ValidateDelete` been triggered?

### ISSUE THREAD

**Issue by HongChenTW** [pingcap/chaos-mesh#457]
## Question

I deployed and launched a `PodChaos` chaos, and it worked perfectly.

And I use `kubectl logs` to show `chaos-controller-manager` pod's log, the webhook `ValidateCreate` triggered when I apply new chaos manifests(e.g. `PodChaos`) and `ValidateUpdate` triggered when schedule jobs execute.

```
2020-04-29T07:29:14.177Z	INFO	podchaos-resource	validate create	{"name": "pod-kill-example"}
2020-04-29T07:29:14.222Z	INFO	podchaos-resource	validate update	{"name": "pod-kill-example"}
```

Why `ValidateDelete` method logs `validate delete` doesn't show up when I delete the `PodChaos` manifest?

https://github.com/pingcap/chaos-mesh/blob/ad4f1204a410422e0a93f3aba6b143f42cee15df/api/v1alpha1/podchaos_webhook.go#L52-L69

### Environment

https://github.com/pingcap/chaos-mesh/wiki/Deploy-Chaos-Mesh#step-3-install-chaos-mesh

- Install in docker environment
- helm version: 3.1.2
- Kubernetes version: 1.12.10
- deploy chaos type: [pod-kill-example.yaml](https://github.com/pingcap/chaos-mesh/blob/master/examples/pod-kill-example.yaml)

**Comment by Gallardot** [comment]
@HongChenTW 

https://github.com/pingcap/chaos-mesh/blob/ad4f1204a410422e0a93f3aba6b143f42cee15df/helm/chaos-mesh/templates/webhook-configuration.yaml#L33-L51

Operations are CREATE and UPDATE, ignore DELETE. Why we ignore DELETE operation? You can check out this [PR338](https://github.com/pingcap/chaos-mesh/pull/338).  We have some discussion about it. If you have any questions, please let me know.

**Comment by Yisaer** [comment]
Feel free to reopen this issue if you have any question.

**Comment by HongChenTW** [comment]
Thanks for your explanation.
