### ISSUE TITLE
iochaos-controller timed out waiting for the condition

### ISSUE THREAD

**Issue by HillebrandtOldenberg** [pingcap/chaos-mesh#463]
## Bug Report

**What version of Kubernetes are you using?**

Client & server: v1.18.0

**What did you do?**

Followed the [manual](https://github.com/pingcap/chaos-mesh/wiki/Deploy-Chaos-Mesh) and then:

1. `kubectl create ns chaos-testing`
2. `kubectl label ns chaos-testing admission-webhook=enabled`
3. `kubectl annotate ns app-ns admission-webhook.pingcap.com/init-request=chaosfs-etcd`
4. `kubectl apply -f https://raw.githubusercontent.com/pingcap/chaos-mesh/master/examples/etcd/etcd-configmap.yaml --namespace chaos-testing`
5. `kubectl apply -f https://raw.githubusercontent.com/pingcap/chaos-mesh/master/examples/etcd/etcd.yaml --namespace chaos-testing`
6. `kubectl apply -f https://raw.githubusercontent.com/pingcap/chaos-mesh/master/examples/etcd/etcd-iochaos.yaml --namespace chaos-testing`

**What did you expect to see?**

`kubectl describe iochaos io-delay-example --namespace chaos-testing`:
```
Status:
  Experiment:
    Phase:  Finished
```

**What did you see instead?**
```
Status:
  Experiment:
    Phase:  Failed
  Phase:
Events:
  Type     Reason             Age   From                Message
  ----     ------             ----  ----                -------
  Warning  ChaosInjectFailed  105s  iochaos-controller  timed out waiting for the condition
```

**Comment by zhouqiang-cl** [comment]
@fewdan is working on this issue

**Comment by HillebrandtOldenberg** [comment]
Oh, okay, thanks for letting me know! Thanks for all your work!

**Comment by HillebrandtOldenberg** [comment]
@fewdan Oh yeah, my bad, wrote it badly in the issue, executed it correctly :)
