### ISSUE TITLE
[Fail] [Basic] [TimeChaos] [TimeSkew] [It] [Schedule] e2e is flaky

### ISSUE THREAD

**Issue by Yisaer** [pingcap/chaos-mesh#464]
## Bug Report

Error happens in e2e: 
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/chaos-mesh-e2e/detail/chaos-mesh-e2e/88/pipeline

**Comment by yeya24** [comment]
Fixed in #449

**Comment by yeya24** [comment]
Close this since #449 is merged.

Feel free to reopen it if this problem still exists
