### ISSUE TITLE
Non-admin user using Chaos-Mesh

### ISSUE THREAD

**Issue by 2020testuser** [pingcap/chaos-mesh#477]
Hi,
Not sure whether the below is really a bug or a feature  request. Please move accordingly if it is not a bug.
Do I need to be a Kubernetes admin user to install Chaos mesh? I'm a non-admin user and wondering whether I can install Chaos Mesh in my own namespace (where I have full access)? Please let me know if this functionality is already available or there is an alternate way to install ChaosMesh in the namespace in Kubernetes.
Thanks!

**Comment by zhouqiang-cl** [comment]
@cwen0 @Yisaer PTAL

**Comment by cwen0** [comment]
@2020testuser Sorry, We need to use a Kubernetes admin user to install Chaos Mesh.

**Comment by Yisaer** [comment]
Currently chaos-mesh required ClusterScope rbac. I think Chaos-mesh also could be running in namespace scoped rbac and Kubernetes admin user is not necessary.

**Comment by 2020testuser** [comment]
Thanks! Want to make  sure that non-admin users cannot install it. Will wait for Chaos Mesh Cloud.

**Comment by 2020testuser** [comment]
Closing as go confirmation. Thanks!
