### ISSUE TITLE
Provide more information after e2e test

### ISSUE THREAD

**Issue by Yisaer** [pingcap/chaos-mesh#488]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, when e2e test failed, we can't get lots useful information excepting running e2e case locally. This issue is to track the improvement of the e2e test to help developers find error online after e2e test finished.

**Comment by yeya24** [comment]
Does https://github.com/pingcap/chaos-mesh/pull/587 fix this issue?  @Yisaer

**Comment by Yisaer** [comment]
Yes, we can close this issue now.
