### ISSUE TITLE
[API] Get the list of the experiments

### ISSUE THREAD

**Issue by fewdan** [pingcap/chaos-mesh#492]
## Feature Request

/experiments/all: Get the list of the experiments

See [here](https://app.swaggerhub.com/apis/ChaosMesh/chaos-server/1.0.0#trial) for details

**Comment by yeya24** [comment]
Is the `experiment_type` the same as `kind`? If so, maybe it is better to rename this param to `kind` to be more unified among APIs.

**Comment by fewdan** [comment]
@yeya24 I think yes, it can be changed to "kind".
