### ISSUE TITLE
Support to trigger experiment by the special event

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#500]
## Feature Request

**Is your feature request related to a problem? Please describe:**
  

At present, we support to trigger experiments base on time scheduler, but sometimes we also need to trigger experiments by the special event, for example, we can trigger experiments by other systems

**Comment by yeya24** [comment]
Can you explain this request in detail? What is the meaning of `trigger experiments by other systems`? Now Chaos Mesh supports the creation API so I assume we can already achieve this?

**Comment by cwen0** [comment]
@yeya24 Yes, you are right. I will close this issue.
