### ISSUE TITLE
New info API for chaosfs sidecar

### ISSUE THREAD

**Issue by yeya24** [pingcap/chaos-mesh#503]
## Feature Request

The current chaosfs sidecar is just like a black box and it is hard to know its current status. The only way I can come up with is to check its logs. However, this is hard to achieve in E2E test.

Now many flaky IO E2E tests happen because it is hard to know whether the chaosfs recovers the fault or not. It would be nice to have such an `Info` grpc API to get the current status of injections.

**Comment by Yisaer** [comment]
Good idea. We can also sync the sidecar information into IOChaos Status.

**Comment by yeya24** [comment]
IMO the IO chaos status should be separated from the sidecar status. They are two different entities.

**Comment by yeya24** [comment]
Actually what I need is just an API to check whether the chaosfs is injected or not and I don't care about the details of injections. So this API only returns a bool value. Is it reasonable? @cwen0 @Yisaer WDYT?

**Comment by Yisaer** [comment]
> Actually what I need is just an API to check whether the chaosfs is injected or not and I don't care about the details of injections. So this API only returns a bool value. Is it reasonable? @cwen0 @Yisaer WDYT?

That's ok to me.
