### ISSUE TITLE
io-chaos experiment error : spec.configName: Required value

### ISSUE THREAD

**Issue by jungle-zh** [pingcap/chaos-mesh#533]
## Bug Report

**What version of Kubernetes are you using?**

1.18.2
**What did you do?**

i was doing the experiment in  chaos-mesh/example/etcd 
my steps:
1.kubectl  apply -f etcd-configmap.yaml
2  kubectl annotate ns chaos-testing admission-webhook.pingcap.com/init-request=chaosfs-etcd
3 kubectl  apply -f etcd.yaml 
4  kubectl apply -f etcd-iochaos.yaml
**What did you expect to see?**
   the etcd  and chaosfs process should be   launched   
**What did you see instead?**
there's no error until step 4 , step 4  report :   
The IoChaos "io-delay-example" is invalid: spec.configName: Required value

**Comment by jungle-zh** [comment]
my fault ,I forgot to update the crd

**Comment by yeya24** [comment]
@jungle-zh Sorry about that. The new IO Chaos implementation is done but I haven't finished its doc.

Note that if you are using the latest master, in order to use IO Chaos, you must apply the configmap `manifests/sidecar-template.yaml` to the same namespace with your chaos mesh controller.
