### ISSUE TITLE
Support --grace-period config for pod-kill

### ISSUE THREAD

**Issue by zhanghuidinah** [pingcap/chaos-mesh#569]
## Feature Request

**Is your feature request related to a problem? Please describe:**
```
Different scenes have different appearance
```
- for network disconnect，--grace-period=0
- for pod or deploy abnorma by itself, --grace-period>0

**Comment by namco1992** [comment]
Hello @cwen0 @zhouqiang-cl , I'm new here and I found the project quite useful and fascinating. I would like to try on this issue but I got a few questions:
1. I get the idea of customising grace period for pod-kill, but I didn't get the 2 scenarios @zhanghuidinah described. For the first scenario, should it be network chaos for network disconnection? Do we want to simulate the network disconnection by killing pods? For the second scenario, why the pod or deployment failure relates to killing pods? Are we trying to simulate the `CrashLoopBackOff` status?
2. If we want to implement this, will the grace period become a field in pod chaos CRD?

Sorry for these many questions and thanks in advance.

**Comment by cwen0** [comment]
@namco1992 
About the first question, the description from @zhanghuidinah may be confusing. 
Normally, when we delete a pod or the pod quits abnormally, the value of `--grace-period` is greater than 0 and Kubernetes will make sure that the pod is actually deleted before deleting this pod object from etcd.  
But if we set `--grace-period=0`, Kubernetes will delete this object from etcd directly. this scenario is similar to the physical node abnormality or network disconnect. You can find more details at here https://kubernetes.io/docs/concepts/workloads/pods/pod/#force-deletion-of-pods. 

At present, Chaos Mesh deletes the pod with `--grace-period=0` to simulate some pods are killed. This way can't meet some injection scenario.  So, we need to support to set `grace-period` option to support different scenes. 

About the second question, I think it is ok to add a field in pod chaos CRD.

**Comment by namco1992** [comment]
@cwen0 Thank you for the clarification, I understand it better now. May I take this issue then?

**Comment by cwen0** [comment]
@namco1992 Of cause, I will assign this issue to you.

**Comment by cwen0** [comment]
@namco1992 How is this issue going? Do you need any help?

**Comment by namco1992** [comment]
@cwen0 Hello, I've done the code changes and trying to test it locally, no blocker so far. I will try to wrap it up by today (UTC +8). I will ask in the slack channel if I encounter any issue. Sorry for dragging it so long. Thanks!

**Comment by cwen0** [comment]
This issue has been solved in #663, We can close this issue.
