### ISSUE TITLE
We can add a status `suspend` in dashboard

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/chaos-mesh#594]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When a cron chaos not in scheduler, Now it display as finished(but actually not finish, it will start later)
We can add a `suspend` here
![企业微信截图_45fb1ca7-541c-4401-9389-a79ed63f9e0c](https://user-images.githubusercontent.com/23521459/83764480-91449c80-a6ac-11ea-86f9-5f822e659590.png)

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by yeya24** [comment]
The `finished` definition is not clear in Chaos Mesh. For a chaos with `cron`, it will never finish. The entity which finishes is the experiment.

We should add a status for `paused` chaos as well

**Comment by g1eny0ung** [comment]
@zhouqiang-cl In PR #612, I have already added a PAUSED Button to solve this issue.

But as @yeya24 said, the `finish` definition is not clear. We need to change the API code to fully solve this problem.
