### ISSUE TITLE
PodKill and ContainerKill should only support schedule mode in frontend

### ISSUE THREAD

**Issue by yeya24** [pingcap/chaos-mesh#596]
## Bug Report

1. Choose podkill or container kill in the `Target` page, then click `Next`
![image](https://user-images.githubusercontent.com/25150124/83825081-445dc780-a6a6-11ea-9a8f-341e6f9e78b1.png)

2. It shows `The action you chose must be immediate`. However podkill and container kill only works at schedule mode so https://github.com/pingcap/chaos-mesh/blob/14493ac9df745ba3b223c541c98e52c76e493879/ui/src/lib/formikhelpers.ts#L76 function just does the opposite thing.
![image](https://user-images.githubusercontent.com/25150124/83825085-4aec3f00-a6a6-11ea-825f-b23bdbd68f8b.png)

**Comment by g1eny0ung** [comment]
Solved in #597.
