### ISSUE TITLE
[API] Support get all labels of the special pods 

### ISSUE THREAD

**Issue by cwen0** [pingcap/chaos-mesh#615]
## Feature Request

**Is your feature request related to a problem? Please describe:**

![image](https://user-images.githubusercontent.com/22956341/84341042-c3865a80-abd4-11ea-90cd-cdc4c5db201b.png)

We can get all labels of the pods and let users select labels instead of filling one. I think this way is more friendly for users. 

**Describe the feature you'd like:**
  

```
URL: /api/common/labels?ns=xxx,xxx 

return 200: 
{
    "app": "xxx", 
    "xxx": "xxxx", 
} 

return 404: 
Not Found

return 500 xxx
```
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by yeya24** [comment]
Why the URL is `URL: /api/common/pods?ns=xxx,xxx`? Is this the same API as `/common/pods`?

**Comment by cwen0** [comment]
> Why the URL is `URL: /api/common/pods?ns=xxx,xxx`? Is this the same API as `/common/pods`?

Sorry, A typo, `URL: /api/common/labels?ns=xxx,xxx`

**Comment by yeya24** [comment]
> > Why the URL is `URL: /api/common/pods?ns=xxx,xxx`? Is this the same API as `/common/pods`?
> 
> Sorry, A typo, `URL: /api/common/labels?ns=xxx,xxx`

Ack. But it is also a good idea to put the labels in the `/common/pods` API, since labels are just pods metadata.
