### ISSUE TITLE
List Events API should support finish time parameter

### ISSUE THREAD

**Issue by yeya24** [pingcap/chaos-mesh#644]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by fewdan** [comment]
Understand, I will deal with this.

**Comment by yeya24** [comment]
I just found that `kind` is not added to events API as well, we should support it
