### ISSUE TITLE
Make scheduler as optional in APIs

### ISSUE THREAD

**Issue by Yisaer** [pingcap/chaos-mesh#72]
I'm trying to use `chaos-mesh` and I found that most APIs have a `scheduler` option and it is also necessary. I think it's weird for some API with `scheduler` and would be hard for users to observe the status of k8s-cluster or tidb-cluster.

For example, if I want to observe the performance of my `distributed system` in `network-partition` situation, I would like to apply a `network-partition` chaos API and it would take effect after the chaos-operator received it.  After this, I can observe my cluster and see how the cluster performs. After the chaos-testing is over, I could delete the `network-partition` API and the network recover as previous.

I think `Scheduler` is also valuable to simulate a weak connection network but not user-friendly for a first quick trial.

**Comment by Yisaer** [comment]
@YangKeao A piece of advice, I found that all of the chaos cases are built by `crd`+`controller` to reconcile the cluster to the expected status. 
I think it is suitable for some chaos cases like `network chaos cases` but not suitable for other cases like `pod kill chaos`.  In these consuming likely cases, I think the HTPP server ( or other server which consumes the request)  to trigger a chaos case would be more reasonable. Building systems on Kubernetes doesn't mean we should make all the APIs as resources, just a bit of advice.

**Comment by zhouqiang-cl** [comment]
agree with @Yisaer
